// @generated by scripts/gen-tenant-scope-maps.ts — DO NOT EDIT BY HAND.
//
// Precomputed tenant-isolation maps for src/lib/tenant-scope.ts. Generated from
// the Prisma DMMF at build time (see scripts/prisma-generate.mjs) so the
// chokepoint NEVER touches `Prisma.dmmf` at runtime — that getter throws in the
// Cloudflare edge runtime. Plain object literals, no `@prisma/client` import:
// safe to load under workerd. Regenerate via `prisma generate` (the prebuild
// runs this). The drift guard test/iso/tenant-scope-maps.test.ts fails if stale.

/** model → (relationField → targetModel), from the generated DMMF. */
export const RELATIONS: Record<string, Record<string, string>> = {
  "User": {
    "activities": "Activity",
    "analyticsEvents": "AnalyticsEvent",
    "bookmarks": "Bookmark",
    "comments": "Comment",
    "connectionsReceived": "Connection",
    "connectionsSent": "Connection",
    "courseEnrollments": "CourseEnrollment",
    "digestLogs": "DigestLog",
    "emailPreferences": "EmailPreference",
    "eventRsvps": "EventRSVP",
    "eventLumaInterests": "EventLumaInterest",
    "lessonProgress": "LessonProgress",
    "likes": "Like",
    "mentions": "Mention",
    "notifications": "Notification",
    "pageViews": "PageView",
    "pollVotes": "PollVote",
    "posts": "Post",
    "subscriptions": "Subscription",
    "userBadges": "UserBadge",
    "emailSends": "EmailSend",
    "tagAssignments": "UserTagAssignment",
    "contactListMemberships": "ContactListMember",
    "automationEnrollments": "AutomationEnrollment",
    "talkSubmissions": "TalkSubmission",
    "talkComments": "TalkComment",
    "socialAccounts": "SocialAccount",
    "socialPosts": "SocialPost",
    "tenantMemberships": "UserTenant"
  },
  "Role": {},
  "Badge": {
    "userBadges": "UserBadge"
  },
  "UserBadge": {
    "badge": "Badge",
    "user": "User"
  },
  "Page": {},
  "City": {},
  "IndustryPage": {},
  "SpaceGroup": {
    "spaces": "Space"
  },
  "Space": {
    "posts": "Post",
    "group": "SpaceGroup",
    "requiredTier": "MembershipTier"
  },
  "Post": {
    "attachments": "Attachment",
    "bookmarks": "Bookmark",
    "comments": "Comment",
    "likes": "Like",
    "mentions": "Mention",
    "poll": "Poll",
    "space": "Space",
    "author": "User",
    "reactions": "Reaction"
  },
  "Comment": {
    "parent": "Comment",
    "replies": "Comment",
    "post": "Post",
    "author": "User",
    "reactions": "CommentReaction"
  },
  "Reaction": {
    "post": "Post"
  },
  "CommentReaction": {
    "comment": "Comment"
  },
  "Like": {
    "post": "Post",
    "user": "User"
  },
  "Event": {
    "rsvps": "EventRSVP",
    "lumaInterests": "EventLumaInterest",
    "resources": "EventResource",
    "agendaItems": "EventAgendaItem",
    "speakers": "Speaker"
  },
  "EventAgendaItem": {
    "event": "Event",
    "speaker": "Speaker",
    "submission": "TalkSubmission"
  },
  "Speaker": {
    "event": "Event",
    "submission": "TalkSubmission",
    "agendaItems": "EventAgendaItem"
  },
  "EventResource": {
    "event": "Event"
  },
  "EventRSVP": {
    "event": "Event",
    "user": "User"
  },
  "EventLumaInterest": {
    "event": "Event",
    "user": "User"
  },
  "Bookmark": {
    "post": "Post",
    "user": "User"
  },
  "Poll": {
    "post": "Post",
    "options": "PollOption"
  },
  "PollOption": {
    "poll": "Poll",
    "votes": "PollVote"
  },
  "PollVote": {
    "option": "PollOption",
    "user": "User"
  },
  "Attachment": {
    "post": "Post"
  },
  "Mention": {
    "post": "Post",
    "user": "User"
  },
  "Activity": {
    "user": "User"
  },
  "Notification": {
    "user": "User"
  },
  "EmailPreference": {
    "user": "User"
  },
  "Course": {
    "requiredTier": "MembershipTier",
    "enrollments": "CourseEnrollment",
    "lessons": "Lesson"
  },
  "Lesson": {
    "course": "Course",
    "progress": "LessonProgress"
  },
  "CourseEnrollment": {
    "course": "Course",
    "user": "User"
  },
  "LessonProgress": {
    "lesson": "Lesson",
    "user": "User"
  },
  "MembershipTier": {
    "courses": "Course",
    "spaces": "Space",
    "subscriptions": "Subscription"
  },
  "Subscription": {
    "tier": "MembershipTier",
    "user": "User"
  },
  "PageView": {
    "user": "User"
  },
  "AnalyticsEvent": {
    "user": "User"
  },
  "DigestLog": {
    "user": "User"
  },
  "Connection": {
    "receiver": "User",
    "requester": "User"
  },
  "LeaderboardLevel": {},
  "EmailCampaign": {
    "sends": "EmailSend",
    "list": "ContactList",
    "trackingEvents": "EmailTrackingEvent",
    "trackedLinks": "EmailTrackedLink",
    "abTest": "EmailABTest"
  },
  "EmailSend": {
    "campaign": "EmailCampaign",
    "user": "User",
    "variant": "EmailABVariant",
    "trackingEvents": "EmailTrackingEvent"
  },
  "EmailSegment": {},
  "EmailTemplate": {},
  "EmailSavedBlock": {},
  "ContactList": {
    "members": "ContactListMember",
    "campaigns": "EmailCampaign"
  },
  "ContactListMember": {
    "list": "ContactList",
    "user": "User"
  },
  "EmailTrackingEvent": {
    "campaign": "EmailCampaign",
    "send": "EmailSend"
  },
  "EmailTrackedLink": {
    "campaign": "EmailCampaign"
  },
  "EmailSuppressionList": {},
  "EmailABTest": {
    "campaign": "EmailCampaign",
    "variants": "EmailABVariant"
  },
  "EmailABVariant": {
    "test": "EmailABTest",
    "sends": "EmailSend"
  },
  "EmailAutomation": {
    "steps": "AutomationStep",
    "enrollments": "AutomationEnrollment"
  },
  "AutomationStep": {
    "automation": "EmailAutomation"
  },
  "AutomationEnrollment": {
    "automation": "EmailAutomation",
    "user": "User"
  },
  "UserTag": {
    "users": "UserTagAssignment"
  },
  "UserTagAssignment": {
    "user": "User",
    "tag": "UserTag"
  },
  "SpaceView": {},
  "ScheduledCourse": {},
  "TalkSubmission": {
    "user": "User",
    "agendaItems": "EventAgendaItem",
    "speakers": "Speaker",
    "comments": "TalkComment"
  },
  "TalkComment": {
    "submission": "TalkSubmission",
    "author": "User"
  },
  "ImpactLabInterest": {},
  "ImpactLabSponsor": {},
  "SlideGeneratorState": {},
  "SlideStylePreset": {},
  "SlideRender": {},
  "SlideExportJob": {},
  "ImpactLabConfig": {},
  "ImpactLabTeam": {
    "participants": "ImpactLabParticipant",
    "peoplesChoiceVotes": "ImpactLabTeamVote"
  },
  "ImpactLabParticipant": {
    "team": "ImpactLabTeam",
    "vote": "ImpactLabVote",
    "peoplesChoiceVote": "ImpactLabTeamVote",
    "coffeeCodeEntry": "ImpactLabCoffeeCode"
  },
  "ImpactLabTeamVote": {
    "participant": "ImpactLabParticipant",
    "team": "ImpactLabTeam"
  },
  "ImpactLabCoffeeCode": {
    "participant": "ImpactLabParticipant"
  },
  "ImpactLabProblemStatement": {
    "votes": "ImpactLabVote"
  },
  "ImpactLabVote": {
    "participant": "ImpactLabParticipant",
    "statement": "ImpactLabProblemStatement"
  },
  "ImpactLabScheduleItem": {},
  "ImpactLabResource": {},
  "SocialAccount": {
    "createdBy": "User",
    "posts": "SocialPost"
  },
  "SocialPost": {
    "account": "SocialAccount",
    "createdBy": "User"
  },
  "Tenant": {
    "settings": "TenantSetting"
  },
  "TenantSetting": {
    "tenant": "Tenant"
  },
  "UserTenant": {
    "user": "User"
  },
  "PendingAdminGrant": {},
  "AuditLog": {}
};

/** model → (scalarFKField → relationField) for FKs targeting a tenant-scoped model. */
export const SCALAR_FK_TO_REL: Record<string, Record<string, string>> = {
  "UserBadge": {
    "badgeId": "badge"
  },
  "Space": {
    "groupId": "group",
    "requiredTierId": "requiredTier"
  },
  "Post": {
    "spaceId": "space"
  },
  "Comment": {
    "parentId": "parent",
    "postId": "post"
  },
  "Reaction": {
    "postId": "post"
  },
  "CommentReaction": {
    "commentId": "comment"
  },
  "Like": {
    "postId": "post"
  },
  "EventAgendaItem": {
    "eventId": "event",
    "speakerId": "speaker",
    "submissionId": "submission"
  },
  "Speaker": {
    "eventId": "event",
    "submissionId": "submission"
  },
  "EventResource": {
    "eventId": "event"
  },
  "EventRSVP": {
    "eventId": "event"
  },
  "EventLumaInterest": {
    "eventId": "event"
  },
  "Bookmark": {
    "postId": "post"
  },
  "Poll": {
    "postId": "post"
  },
  "PollOption": {
    "pollId": "poll"
  },
  "PollVote": {
    "optionId": "option"
  },
  "Attachment": {
    "postId": "post"
  },
  "Mention": {
    "postId": "post"
  },
  "Course": {
    "requiredTierId": "requiredTier"
  },
  "Lesson": {
    "courseId": "course"
  },
  "CourseEnrollment": {
    "courseId": "course"
  },
  "LessonProgress": {
    "lessonId": "lesson"
  },
  "Subscription": {
    "tierId": "tier"
  },
  "EmailCampaign": {
    "listId": "list"
  },
  "EmailSend": {
    "campaignId": "campaign",
    "variantId": "variant"
  },
  "ContactListMember": {
    "listId": "list"
  },
  "EmailTrackingEvent": {
    "campaignId": "campaign",
    "sendId": "send"
  },
  "EmailTrackedLink": {
    "campaignId": "campaign"
  },
  "EmailABTest": {
    "campaignId": "campaign"
  },
  "EmailABVariant": {
    "testId": "test"
  },
  "AutomationStep": {
    "automationId": "automation"
  },
  "AutomationEnrollment": {
    "automationId": "automation"
  },
  "UserTagAssignment": {
    "tagId": "tag"
  },
  "TalkComment": {
    "submissionId": "submission"
  },
  "SocialPost": {
    "accountId": "account"
  }
};
