/* eslint-disable */
// Generated by `wrangler types` — keep a hand-written baseline so typecheck works pre-install.
interface Env {
  REGISTRY: D1Database;
  TENANT_SYDNEY: D1Database;
  TENANT_MELBOURNE: D1Database;
  STORAGE: R2Bucket;
  BROWSER: Fetcher;
  PUBLISH_POST: Workflow;
  SLIDE_EXPORT: Workflow;
  CAMPAIGN_SEND: Workflow;
  MAINTENANCE_MODE?: string;
  MAINTENANCE_BYPASS_TOKEN?: string;
  VITE_REGION?: string;
  VITE_CLERK_PUBLISHABLE_KEY?: string;
  CLERK_PUBLISHABLE_KEY?: string;
  CLERK_SECRET_KEY?: string;
  RESEND_API_KEY?: string;
  RESEND_WEBHOOK_SECRET?: string;
  RENDER_SIGNING_SECRET?: string;
}
