/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// Temporary stub — regenerated by TanStack Router Vite plugin on `vite dev` / `vite build`.
import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ApiHealthRouteImport } from "./routes/api/health"
import { Route as ApiMcpRouteImport } from "./routes/api/mcp"
import { Route as ApiUploadRouteImport } from "./routes/api/upload"
import { Route as ApiFilesRouteImport } from "./routes/api/files.$"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as CitySlugRouteImport } from "./routes/$citySlug/route"
import { Route as CitySlugIndexRouteImport } from "./routes/$citySlug/index"
import { Route as CitySlugEventsIndexRouteImport } from "./routes/$citySlug/events/index"
import { Route as CitySlugCommunityIndexRouteImport } from "./routes/$citySlug/community/index"
import { Route as CitySlugAdminIndexRouteImport } from "./routes/$citySlug/admin/index"

const IndexRoute = IndexRouteImport.update({ id: "/", path: "/", getParentRoute: () => rootRouteImport })
const ApiHealthRoute = ApiHealthRouteImport.update({ id: "/api/health", path: "/api/health", getParentRoute: () => rootRouteImport })
const ApiMcpRoute = ApiMcpRouteImport.update({ id: "/api/mcp", path: "/api/mcp", getParentRoute: () => rootRouteImport })
const ApiUploadRoute = ApiUploadRouteImport.update({ id: "/api/upload", path: "/api/upload", getParentRoute: () => rootRouteImport })
const ApiFilesRoute = ApiFilesRouteImport.update({ id: "/api/files/$", path: "/api/files/$", getParentRoute: () => rootRouteImport })
const AdminIndexRoute = AdminIndexRouteImport.update({ id: "/admin/", path: "/admin/", getParentRoute: () => rootRouteImport })
const CitySlugRoute = CitySlugRouteImport.update({ id: "/$citySlug", path: "/$citySlug", getParentRoute: () => rootRouteImport })
const CitySlugIndexRoute = CitySlugIndexRouteImport.update({ id: "/", path: "/", getParentRoute: () => CitySlugRoute })
const CitySlugEventsIndexRoute = CitySlugEventsIndexRouteImport.update({ id: "/events/", path: "/events/", getParentRoute: () => CitySlugRoute })
const CitySlugCommunityIndexRoute = CitySlugCommunityIndexRouteImport.update({ id: "/community/", path: "/community/", getParentRoute: () => CitySlugRoute })
const CitySlugAdminIndexRoute = CitySlugAdminIndexRouteImport.update({ id: "/admin/", path: "/admin/", getParentRoute: () => CitySlugRoute })

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/api/health": typeof ApiHealthRoute
  "/api/mcp": typeof ApiMcpRoute
  "/api/upload": typeof ApiUploadRoute
  "/api/files/$": typeof ApiFilesRoute
  "/admin": typeof AdminIndexRoute
  "/$citySlug": typeof CitySlugRouteWithChildren
  "/$citySlug/": typeof CitySlugIndexRoute
  "/$citySlug/events": typeof CitySlugEventsIndexRoute
  "/$citySlug/community": typeof CitySlugCommunityIndexRoute
  "/$citySlug/admin": typeof CitySlugAdminIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/api/health": typeof ApiHealthRoute
  "/api/mcp": typeof ApiMcpRoute
  "/api/upload": typeof ApiUploadRoute
  "/api/files/$": typeof ApiFilesRoute
  "/admin/": typeof AdminIndexRoute
  "/$citySlug": typeof CitySlugRouteWithChildren
  "/$citySlug/": typeof CitySlugIndexRoute
  "/$citySlug/events/": typeof CitySlugEventsIndexRoute
  "/$citySlug/community/": typeof CitySlugCommunityIndexRoute
  "/$citySlug/admin/": typeof CitySlugAdminIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/api/health"
    | "/api/mcp"
    | "/api/upload"
    | "/api/files/$"
    | "/admin"
    | "/$citySlug"
    | "/$citySlug/"
    | "/$citySlug/events"
    | "/$citySlug/community"
    | "/$citySlug/admin"
  fileRoutesById: FileRoutesById
  id:
    | "__root__"
    | "/"
    | "/api/health"
    | "/api/mcp"
    | "/api/upload"
    | "/api/files/$"
    | "/admin/"
    | "/$citySlug"
    | "/$citySlug/"
    | "/$citySlug/events/"
    | "/$citySlug/community/"
    | "/$citySlug/admin/"
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { id: "/"; path: "/"; fullPath: "/"; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    "/api/health": { id: "/api/health"; path: "/api/health"; fullPath: "/api/health"; preLoaderRoute: typeof ApiHealthRouteImport; parentRoute: typeof rootRouteImport }
    "/api/mcp": { id: "/api/mcp"; path: "/api/mcp"; fullPath: "/api/mcp"; preLoaderRoute: typeof ApiMcpRouteImport; parentRoute: typeof rootRouteImport }
    "/api/upload": { id: "/api/upload"; path: "/api/upload"; fullPath: "/api/upload"; preLoaderRoute: typeof ApiUploadRouteImport; parentRoute: typeof rootRouteImport }
    "/api/files/$": { id: "/api/files/$"; path: "/api/files/$"; fullPath: "/api/files/$"; preLoaderRoute: typeof ApiFilesRouteImport; parentRoute: typeof rootRouteImport }
    "/admin/": { id: "/admin/"; path: "/admin"; fullPath: "/admin"; preLoaderRoute: typeof AdminIndexRouteImport; parentRoute: typeof rootRouteImport }
    "/$citySlug": { id: "/$citySlug"; path: "/$citySlug"; fullPath: "/$citySlug"; preLoaderRoute: typeof CitySlugRouteImport; parentRoute: typeof rootRouteImport }
    "/$citySlug/": { id: "/$citySlug/"; path: "/"; fullPath: "/$citySlug/"; preLoaderRoute: typeof CitySlugIndexRouteImport; parentRoute: typeof CitySlugRoute }
    "/$citySlug/events/": { id: "/$citySlug/events/"; path: "/events"; fullPath: "/$citySlug/events"; preLoaderRoute: typeof CitySlugEventsIndexRouteImport; parentRoute: typeof CitySlugRoute }
    "/$citySlug/community/": { id: "/$citySlug/community/"; path: "/community"; fullPath: "/$citySlug/community"; preLoaderRoute: typeof CitySlugCommunityIndexRouteImport; parentRoute: typeof CitySlugRoute }
    "/$citySlug/admin/": { id: "/$citySlug/admin/"; path: "/admin"; fullPath: "/$citySlug/admin"; preLoaderRoute: typeof CitySlugAdminIndexRouteImport; parentRoute: typeof CitySlugRoute }
  }
}

const CitySlugRouteWithChildren = CitySlugRoute._addFileChildren({
  CitySlugIndexRoute,
  CitySlugEventsIndexRoute,
  CitySlugCommunityIndexRoute,
  CitySlugAdminIndexRoute,
})

const rootRouteChildren = {
  IndexRoute,
  ApiHealthRoute,
  ApiMcpRoute,
  ApiUploadRoute,
  ApiFilesRoute,
  AdminIndexRoute,
  CitySlugRoute: CitySlugRouteWithChildren,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
/* prettier-ignore-end */
