/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitySlugRouteRouteImport } from './routes/$citySlug/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RemotionRouteImport } from './routes/remotion'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as CitySlugIndexRouteImport } from './routes/$citySlug/index'
import { Route as CitySlugAdminRouteRouteImport } from './routes/$citySlug/admin/route'
import { Route as CitySlugCommunityRouteRouteImport } from './routes/$citySlug/community/route'
import { Route as CitySlugCoworkRouteImport } from './routes/$citySlug/cowork'
import { Route as CitySlugMembershipRouteImport } from './routes/$citySlug/membership'
import { Route as CitySlugMerchRouteImport } from './routes/$citySlug/merch'
import { Route as CitySlugProfessionalsRouteImport } from './routes/$citySlug/professionals'
import { Route as CitySlugVibeCodersRouteImport } from './routes/$citySlug/vibe-coders'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as LoginSsoCallbackRouteImport } from './routes/login/sso-callback'
import { Route as SignupSsoCallbackRouteImport } from './routes/signup/sso-callback'
import { Route as CitySlugAdminIndexRouteImport } from './routes/$citySlug/admin/index'
import { Route as CitySlugAdminAnalyticsRouteImport } from './routes/$citySlug/admin/analytics'
import { Route as CitySlugAdminBadgesRouteImport } from './routes/$citySlug/admin/badges'
import { Route as CitySlugAdminCitiesRouteImport } from './routes/$citySlug/admin/cities'
import { Route as CitySlugAdminImportRouteImport } from './routes/$citySlug/admin/import'
import { Route as CitySlugAdminInviteRouteImport } from './routes/$citySlug/admin/invite'
import { Route as CitySlugAdminPostsRouteImport } from './routes/$citySlug/admin/posts'
import { Route as CitySlugAdminRolesRouteImport } from './routes/$citySlug/admin/roles'
import { Route as CitySlugAdminSettingsRouteImport } from './routes/$citySlug/admin/settings'
import { Route as CitySlugAdminSpeakersRouteImport } from './routes/$citySlug/admin/speakers'
import { Route as CitySlugAdminTiersRouteImport } from './routes/$citySlug/admin/tiers'
import { Route as CitySlugAdminUsersRouteImport } from './routes/$citySlug/admin/users'
import { Route as CitySlugCitiesSlugRouteImport } from './routes/$citySlug/cities/$slug'
import { Route as CitySlugCommunityIndexRouteImport } from './routes/$citySlug/community/index'
import { Route as CitySlugCommunityBookmarksRouteImport } from './routes/$citySlug/community/bookmarks'
import { Route as CitySlugCommunityBugReportRouteImport } from './routes/$citySlug/community/bug-report'
import { Route as CitySlugCommunityConnectionsRouteImport } from './routes/$citySlug/community/connections'
import { Route as CitySlugCommunityEventsRouteImport } from './routes/$citySlug/community/events'
import { Route as CitySlugCommunityGuidelinesRouteImport } from './routes/$citySlug/community/guidelines'
import { Route as CitySlugCommunityLeaderboardRouteImport } from './routes/$citySlug/community/leaderboard'
import { Route as CitySlugCommunityMembersRouteImport } from './routes/$citySlug/community/members'
import { Route as CitySlugCommunityNotificationsRouteImport } from './routes/$citySlug/community/notifications'
import { Route as CitySlugCommunitySearchRouteImport } from './routes/$citySlug/community/search'
import { Route as CitySlugCoursesIndexRouteImport } from './routes/$citySlug/courses/index'
import { Route as CitySlugCoursesSlugRouteImport } from './routes/$citySlug/courses/$slug'
import { Route as CitySlugEventsIndexRouteImport } from './routes/$citySlug/events/index'
import { Route as CitySlugForIndexRouteImport } from './routes/$citySlug/for/index'
import { Route as CitySlugForSlugRouteImport } from './routes/$citySlug/for/$slug'
import { Route as CitySlugImpactLabIndexRouteImport } from './routes/$citySlug/impact-lab/index'
import { Route as CitySlugImpactLabAdminRouteImport } from './routes/$citySlug/impact-lab/admin'
import { Route as CitySlugImpactLabPortalRouteImport } from './routes/$citySlug/impact-lab/portal'
import { Route as CitySlugMyTalksIndexRouteImport } from './routes/$citySlug/my-talks/index'
import { Route as CitySlugMyTalksIdRouteImport } from './routes/$citySlug/my-talks/$id'
import { Route as CitySlugPSplatRouteImport } from './routes/$citySlug/p/$'
import { Route as CitySlugResourcesIndexRouteImport } from './routes/$citySlug/resources/index'
import { Route as CitySlugResourcesSlugRouteImport } from './routes/$citySlug/resources/$slug'
import { Route as CitySlugSpeakIndexRouteImport } from './routes/$citySlug/speak/index'
import { Route as CitySlugWebinarsClaudeCodeWebinarAustraliaRouteImport } from './routes/$citySlug/webinars/claude-code-webinar-australia'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files.$'
import { Route as CitySlugAdminCoursesIndexRouteImport } from './routes/$citySlug/admin/courses/index'
import { Route as CitySlugAdminCoursesNewRouteImport } from './routes/$citySlug/admin/courses/new'
import { Route as CitySlugAdminEmailIndexRouteImport } from './routes/$citySlug/admin/email/index'
import { Route as CitySlugAdminEmailIdRouteImport } from './routes/$citySlug/admin/email/$id'
import { Route as CitySlugAdminEmailAnalyticsRouteImport } from './routes/$citySlug/admin/email/analytics'
import { Route as CitySlugAdminEmailAutomationsRouteImport } from './routes/$citySlug/admin/email/automations'
import { Route as CitySlugAdminEmailContactsRouteImport } from './routes/$citySlug/admin/email/contacts'
import { Route as CitySlugAdminEmailNewRouteImport } from './routes/$citySlug/admin/email/new'
import { Route as CitySlugAdminEmailSettingsRouteImport } from './routes/$citySlug/admin/email/settings'
import { Route as CitySlugAdminEmailTemplatesRouteImport } from './routes/$citySlug/admin/email/templates'
import { Route as CitySlugAdminEventsIndexRouteImport } from './routes/$citySlug/admin/events/index'
import { Route as CitySlugAdminEventsNewRouteImport } from './routes/$citySlug/admin/events/new'
import { Route as CitySlugAdminIndustriesIndexRouteImport } from './routes/$citySlug/admin/industries/index'
import { Route as CitySlugAdminIndustriesSlugRouteImport } from './routes/$citySlug/admin/industries/$slug'
import { Route as CitySlugAdminIndustriesNewRouteImport } from './routes/$citySlug/admin/industries/new'
import { Route as CitySlugAdminPagesIndexRouteImport } from './routes/$citySlug/admin/pages/index'
import { Route as CitySlugAdminPagesIdRouteImport } from './routes/$citySlug/admin/pages/$id'
import { Route as CitySlugAdminPagesHomeRouteImport } from './routes/$citySlug/admin/pages/home'
import { Route as CitySlugAdminPagesNewRouteImport } from './routes/$citySlug/admin/pages/new'
import { Route as CitySlugAdminSocialIndexRouteImport } from './routes/$citySlug/admin/social/index'
import { Route as CitySlugAdminSocialSettingsRouteImport } from './routes/$citySlug/admin/social/settings'
import { Route as CitySlugAdminToolsIndexRouteImport } from './routes/$citySlug/admin/tools/index'
import { Route as CitySlugAdminToolsAttendancePlannerRouteImport } from './routes/$citySlug/admin/tools/attendance-planner'
import { Route as CitySlugAdminToolsAttendeeAnalyticsRouteImport } from './routes/$citySlug/admin/tools/attendee-analytics'
import { Route as CitySlugAdminToolsQrGeneratorRouteImport } from './routes/$citySlug/admin/tools/qr-generator'
import { Route as CitySlugAdminToolsSlideGeneratorRouteImport } from './routes/$citySlug/admin/tools/slide-generator'
import { Route as CitySlugCommunityLearnIndexRouteImport } from './routes/$citySlug/community/learn/index'
import { Route as CitySlugCommunityPostsIdRouteImport } from './routes/$citySlug/community/posts/$id'
import { Route as CitySlugCommunityProfileIndexRouteImport } from './routes/$citySlug/community/profile/index'
import { Route as CitySlugCommunityProfileIdRouteImport } from './routes/$citySlug/community/profile/$id'
import { Route as CitySlugCommunitySettingsNotificationsRouteImport } from './routes/$citySlug/community/settings/notifications'
import { Route as CitySlugCommunitySettingsProfileRouteImport } from './routes/$citySlug/community/settings/profile'
import { Route as CitySlugEventsSlugIndexRouteImport } from './routes/$citySlug/events/$slug/index'
import { Route as CitySlugEventsSlugResourcesRouteImport } from './routes/$citySlug/events/$slug/resources'
import { Route as CitySlugEventsClaudeImpactLabMelbourneIndexRouteImport } from './routes/$citySlug/events/claude-impact-lab-melbourne/index'
import { Route as CitySlugEventsClaudeImpactLabMelbourneSponsorRouteImport } from './routes/$citySlug/events/claude-impact-lab-melbourne/sponsor'
import { Route as CitySlugAdminCoursesIdEditRouteImport } from './routes/$citySlug/admin/courses/$id/edit'
import { Route as CitySlugCommunityLearnSlugIndexRouteImport } from './routes/$citySlug/community/learn/$slug/index'
import { Route as CitySlugCommunityLearnSlugLessonRouteImport } from './routes/$citySlug/community/learn/$slug/$lesson'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRouteRoute = CitySlugRouteRouteImport.update({
  id: '/$citySlug',
  path: '/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RemotionRoute = RemotionRouteImport.update({
  id: '/remotion',
  path: '/remotion',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugIndexRoute = CitySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugAdminRouteRoute = CitySlugAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugCommunityRouteRoute = CitySlugCommunityRouteRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugCoworkRoute = CitySlugCoworkRouteImport.update({
  id: '/cowork',
  path: '/cowork',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugMembershipRoute = CitySlugMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugMerchRoute = CitySlugMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugProfessionalsRoute = CitySlugProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugVibeCodersRoute = CitySlugVibeCodersRouteImport.update({
  id: '/vibe-coders',
  path: '/vibe-coders',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSsoCallbackRoute = LoginSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => LoginRoute,
} as any)
const SignupSsoCallbackRoute = SignupSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignupRoute,
} as any)
const CitySlugAdminIndexRoute = CitySlugAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminAnalyticsRoute = CitySlugAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminBadgesRoute = CitySlugAdminBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminCitiesRoute = CitySlugAdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminImportRoute = CitySlugAdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminInviteRoute = CitySlugAdminInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminPostsRoute = CitySlugAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminRolesRoute = CitySlugAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminSettingsRoute = CitySlugAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminSpeakersRoute = CitySlugAdminSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminTiersRoute = CitySlugAdminTiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminUsersRoute = CitySlugAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugCitiesSlugRoute = CitySlugCitiesSlugRouteImport.update({
  id: '/cities/$slug',
  path: '/cities/$slug',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugCommunityIndexRoute = CitySlugCommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitySlugCommunityRouteRoute,
} as any)
const CitySlugCommunityBookmarksRoute =
  CitySlugCommunityBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunityBugReportRoute =
  CitySlugCommunityBugReportRouteImport.update({
    id: '/bug-report',
    path: '/bug-report',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunityConnectionsRoute =
  CitySlugCommunityConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunityEventsRoute = CitySlugCommunityEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CitySlugCommunityRouteRoute,
} as any)
const CitySlugCommunityGuidelinesRoute =
  CitySlugCommunityGuidelinesRouteImport.update({
    id: '/guidelines',
    path: '/guidelines',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunityLeaderboardRoute =
  CitySlugCommunityLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunityMembersRoute =
  CitySlugCommunityMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunityNotificationsRoute =
  CitySlugCommunityNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunitySearchRoute = CitySlugCommunitySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CitySlugCommunityRouteRoute,
} as any)
const CitySlugCoursesIndexRoute = CitySlugCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugCoursesSlugRoute = CitySlugCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugEventsIndexRoute = CitySlugEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugForIndexRoute = CitySlugForIndexRouteImport.update({
  id: '/for/',
  path: '/for/',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugForSlugRoute = CitySlugForSlugRouteImport.update({
  id: '/for/$slug',
  path: '/for/$slug',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugImpactLabIndexRoute = CitySlugImpactLabIndexRouteImport.update({
  id: '/impact-lab/',
  path: '/impact-lab/',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugImpactLabAdminRoute = CitySlugImpactLabAdminRouteImport.update({
  id: '/impact-lab/admin',
  path: '/impact-lab/admin',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugImpactLabPortalRoute = CitySlugImpactLabPortalRouteImport.update({
  id: '/impact-lab/portal',
  path: '/impact-lab/portal',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugMyTalksIndexRoute = CitySlugMyTalksIndexRouteImport.update({
  id: '/my-talks/',
  path: '/my-talks/',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugMyTalksIdRoute = CitySlugMyTalksIdRouteImport.update({
  id: '/my-talks/$id',
  path: '/my-talks/$id',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugPSplatRoute = CitySlugPSplatRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugResourcesIndexRoute = CitySlugResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugResourcesSlugRoute = CitySlugResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugSpeakIndexRoute = CitySlugSpeakIndexRouteImport.update({
  id: '/speak/',
  path: '/speak/',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugWebinarsClaudeCodeWebinarAustraliaRoute =
  CitySlugWebinarsClaudeCodeWebinarAustraliaRouteImport.update({
    id: '/webinars/claude-code-webinar-australia',
    path: '/webinars/claude-code-webinar-australia',
    getParentRoute: () => CitySlugRouteRoute,
  } as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugAdminCoursesIndexRoute =
  CitySlugAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminCoursesNewRoute = CitySlugAdminCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminEmailIndexRoute = CitySlugAdminEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminEmailIdRoute = CitySlugAdminEmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminEmailAnalyticsRoute =
  CitySlugAdminEmailAnalyticsRouteImport.update({
    id: '/email/analytics',
    path: '/email/analytics',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminEmailAutomationsRoute =
  CitySlugAdminEmailAutomationsRouteImport.update({
    id: '/email/automations',
    path: '/email/automations',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminEmailContactsRoute =
  CitySlugAdminEmailContactsRouteImport.update({
    id: '/email/contacts',
    path: '/email/contacts',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminEmailNewRoute = CitySlugAdminEmailNewRouteImport.update({
  id: '/email/new',
  path: '/email/new',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminEmailSettingsRoute =
  CitySlugAdminEmailSettingsRouteImport.update({
    id: '/email/settings',
    path: '/email/settings',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminEmailTemplatesRoute =
  CitySlugAdminEmailTemplatesRouteImport.update({
    id: '/email/templates',
    path: '/email/templates',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminEventsIndexRoute =
  CitySlugAdminEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminEventsNewRoute = CitySlugAdminEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminIndustriesIndexRoute =
  CitySlugAdminIndustriesIndexRouteImport.update({
    id: '/industries/',
    path: '/industries/',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminIndustriesSlugRoute =
  CitySlugAdminIndustriesSlugRouteImport.update({
    id: '/industries/$slug',
    path: '/industries/$slug',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminIndustriesNewRoute =
  CitySlugAdminIndustriesNewRouteImport.update({
    id: '/industries/new',
    path: '/industries/new',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminPagesIndexRoute = CitySlugAdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminPagesIdRoute = CitySlugAdminPagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminPagesHomeRoute = CitySlugAdminPagesHomeRouteImport.update({
  id: '/pages/home',
  path: '/pages/home',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminPagesNewRoute = CitySlugAdminPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminSocialIndexRoute =
  CitySlugAdminSocialIndexRouteImport.update({
    id: '/social/',
    path: '/social/',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminSocialSettingsRoute =
  CitySlugAdminSocialSettingsRouteImport.update({
    id: '/social/settings',
    path: '/social/settings',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminToolsIndexRoute = CitySlugAdminToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => CitySlugAdminRouteRoute,
} as any)
const CitySlugAdminToolsAttendancePlannerRoute =
  CitySlugAdminToolsAttendancePlannerRouteImport.update({
    id: '/tools/attendance-planner',
    path: '/tools/attendance-planner',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminToolsAttendeeAnalyticsRoute =
  CitySlugAdminToolsAttendeeAnalyticsRouteImport.update({
    id: '/tools/attendee-analytics',
    path: '/tools/attendee-analytics',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminToolsQrGeneratorRoute =
  CitySlugAdminToolsQrGeneratorRouteImport.update({
    id: '/tools/qr-generator',
    path: '/tools/qr-generator',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugAdminToolsSlideGeneratorRoute =
  CitySlugAdminToolsSlideGeneratorRouteImport.update({
    id: '/tools/slide-generator',
    path: '/tools/slide-generator',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugCommunityLearnIndexRoute =
  CitySlugCommunityLearnIndexRouteImport.update({
    id: '/learn/',
    path: '/learn/',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunityPostsIdRoute =
  CitySlugCommunityPostsIdRouteImport.update({
    id: '/posts/$id',
    path: '/posts/$id',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunityProfileIndexRoute =
  CitySlugCommunityProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunityProfileIdRoute =
  CitySlugCommunityProfileIdRouteImport.update({
    id: '/profile/$id',
    path: '/profile/$id',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunitySettingsNotificationsRoute =
  CitySlugCommunitySettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunitySettingsProfileRoute =
  CitySlugCommunitySettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugEventsSlugIndexRoute = CitySlugEventsSlugIndexRouteImport.update({
  id: '/events/$slug/',
  path: '/events/$slug/',
  getParentRoute: () => CitySlugRouteRoute,
} as any)
const CitySlugEventsSlugResourcesRoute =
  CitySlugEventsSlugResourcesRouteImport.update({
    id: '/events/$slug/resources',
    path: '/events/$slug/resources',
    getParentRoute: () => CitySlugRouteRoute,
  } as any)
const CitySlugEventsClaudeImpactLabMelbourneIndexRoute =
  CitySlugEventsClaudeImpactLabMelbourneIndexRouteImport.update({
    id: '/events/claude-impact-lab-melbourne/',
    path: '/events/claude-impact-lab-melbourne/',
    getParentRoute: () => CitySlugRouteRoute,
  } as any)
const CitySlugEventsClaudeImpactLabMelbourneSponsorRoute =
  CitySlugEventsClaudeImpactLabMelbourneSponsorRouteImport.update({
    id: '/events/claude-impact-lab-melbourne/sponsor',
    path: '/events/claude-impact-lab-melbourne/sponsor',
    getParentRoute: () => CitySlugRouteRoute,
  } as any)
const CitySlugAdminCoursesIdEditRoute =
  CitySlugAdminCoursesIdEditRouteImport.update({
    id: '/courses/$id/edit',
    path: '/courses/$id/edit',
    getParentRoute: () => CitySlugAdminRouteRoute,
  } as any)
const CitySlugCommunityLearnSlugIndexRoute =
  CitySlugCommunityLearnSlugIndexRouteImport.update({
    id: '/learn/$slug/',
    path: '/learn/$slug/',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)
const CitySlugCommunityLearnSlugLessonRoute =
  CitySlugCommunityLearnSlugLessonRouteImport.update({
    id: '/learn/$slug/$lesson',
    path: '/learn/$slug/$lesson',
    getParentRoute: () => CitySlugCommunityRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRouteRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/offline': typeof OfflineRoute
  '/pricing': typeof PricingRoute
  '/remotion': typeof RemotionRoute
  '/signup': typeof SignupRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/$citySlug/admin': typeof CitySlugAdminRouteRouteWithChildren
  '/$citySlug/community': typeof CitySlugCommunityRouteRouteWithChildren
  '/$citySlug/cowork': typeof CitySlugCoworkRoute
  '/$citySlug/membership': typeof CitySlugMembershipRoute
  '/$citySlug/merch': typeof CitySlugMerchRoute
  '/$citySlug/professionals': typeof CitySlugProfessionalsRoute
  '/$citySlug/vibe-coders': typeof CitySlugVibeCodersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/upload': typeof ApiUploadRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/signup/sso-callback': typeof SignupSsoCallbackRoute
  '/$citySlug/': typeof CitySlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$citySlug/admin/analytics': typeof CitySlugAdminAnalyticsRoute
  '/$citySlug/admin/badges': typeof CitySlugAdminBadgesRoute
  '/$citySlug/admin/cities': typeof CitySlugAdminCitiesRoute
  '/$citySlug/admin/import': typeof CitySlugAdminImportRoute
  '/$citySlug/admin/invite': typeof CitySlugAdminInviteRoute
  '/$citySlug/admin/posts': typeof CitySlugAdminPostsRoute
  '/$citySlug/admin/roles': typeof CitySlugAdminRolesRoute
  '/$citySlug/admin/settings': typeof CitySlugAdminSettingsRoute
  '/$citySlug/admin/speakers': typeof CitySlugAdminSpeakersRoute
  '/$citySlug/admin/tiers': typeof CitySlugAdminTiersRoute
  '/$citySlug/admin/users': typeof CitySlugAdminUsersRoute
  '/$citySlug/cities/$slug': typeof CitySlugCitiesSlugRoute
  '/$citySlug/community/bookmarks': typeof CitySlugCommunityBookmarksRoute
  '/$citySlug/community/bug-report': typeof CitySlugCommunityBugReportRoute
  '/$citySlug/community/connections': typeof CitySlugCommunityConnectionsRoute
  '/$citySlug/community/events': typeof CitySlugCommunityEventsRoute
  '/$citySlug/community/guidelines': typeof CitySlugCommunityGuidelinesRoute
  '/$citySlug/community/leaderboard': typeof CitySlugCommunityLeaderboardRoute
  '/$citySlug/community/members': typeof CitySlugCommunityMembersRoute
  '/$citySlug/community/notifications': typeof CitySlugCommunityNotificationsRoute
  '/$citySlug/community/search': typeof CitySlugCommunitySearchRoute
  '/$citySlug/courses/$slug': typeof CitySlugCoursesSlugRoute
  '/$citySlug/for/$slug': typeof CitySlugForSlugRoute
  '/$citySlug/impact-lab/admin': typeof CitySlugImpactLabAdminRoute
  '/$citySlug/impact-lab/portal': typeof CitySlugImpactLabPortalRoute
  '/$citySlug/my-talks/$id': typeof CitySlugMyTalksIdRoute
  '/$citySlug/p/$': typeof CitySlugPSplatRoute
  '/$citySlug/resources/$slug': typeof CitySlugResourcesSlugRoute
  '/$citySlug/webinars/claude-code-webinar-australia': typeof CitySlugWebinarsClaudeCodeWebinarAustraliaRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/$citySlug/admin/': typeof CitySlugAdminIndexRoute
  '/$citySlug/community/': typeof CitySlugCommunityIndexRoute
  '/$citySlug/courses/': typeof CitySlugCoursesIndexRoute
  '/$citySlug/events/': typeof CitySlugEventsIndexRoute
  '/$citySlug/for/': typeof CitySlugForIndexRoute
  '/$citySlug/impact-lab/': typeof CitySlugImpactLabIndexRoute
  '/$citySlug/my-talks/': typeof CitySlugMyTalksIndexRoute
  '/$citySlug/resources/': typeof CitySlugResourcesIndexRoute
  '/$citySlug/speak/': typeof CitySlugSpeakIndexRoute
  '/$citySlug/admin/courses/new': typeof CitySlugAdminCoursesNewRoute
  '/$citySlug/admin/email/$id': typeof CitySlugAdminEmailIdRoute
  '/$citySlug/admin/email/analytics': typeof CitySlugAdminEmailAnalyticsRoute
  '/$citySlug/admin/email/automations': typeof CitySlugAdminEmailAutomationsRoute
  '/$citySlug/admin/email/contacts': typeof CitySlugAdminEmailContactsRoute
  '/$citySlug/admin/email/new': typeof CitySlugAdminEmailNewRoute
  '/$citySlug/admin/email/settings': typeof CitySlugAdminEmailSettingsRoute
  '/$citySlug/admin/email/templates': typeof CitySlugAdminEmailTemplatesRoute
  '/$citySlug/admin/events/new': typeof CitySlugAdminEventsNewRoute
  '/$citySlug/admin/industries/$slug': typeof CitySlugAdminIndustriesSlugRoute
  '/$citySlug/admin/industries/new': typeof CitySlugAdminIndustriesNewRoute
  '/$citySlug/admin/pages/$id': typeof CitySlugAdminPagesIdRoute
  '/$citySlug/admin/pages/home': typeof CitySlugAdminPagesHomeRoute
  '/$citySlug/admin/pages/new': typeof CitySlugAdminPagesNewRoute
  '/$citySlug/admin/social/settings': typeof CitySlugAdminSocialSettingsRoute
  '/$citySlug/admin/tools/attendance-planner': typeof CitySlugAdminToolsAttendancePlannerRoute
  '/$citySlug/admin/tools/attendee-analytics': typeof CitySlugAdminToolsAttendeeAnalyticsRoute
  '/$citySlug/admin/tools/qr-generator': typeof CitySlugAdminToolsQrGeneratorRoute
  '/$citySlug/admin/tools/slide-generator': typeof CitySlugAdminToolsSlideGeneratorRoute
  '/$citySlug/community/posts/$id': typeof CitySlugCommunityPostsIdRoute
  '/$citySlug/community/profile/$id': typeof CitySlugCommunityProfileIdRoute
  '/$citySlug/community/settings/notifications': typeof CitySlugCommunitySettingsNotificationsRoute
  '/$citySlug/community/settings/profile': typeof CitySlugCommunitySettingsProfileRoute
  '/$citySlug/events/$slug/resources': typeof CitySlugEventsSlugResourcesRoute
  '/$citySlug/events/claude-impact-lab-melbourne/sponsor': typeof CitySlugEventsClaudeImpactLabMelbourneSponsorRoute
  '/$citySlug/admin/courses/': typeof CitySlugAdminCoursesIndexRoute
  '/$citySlug/admin/email/': typeof CitySlugAdminEmailIndexRoute
  '/$citySlug/admin/events/': typeof CitySlugAdminEventsIndexRoute
  '/$citySlug/admin/industries/': typeof CitySlugAdminIndustriesIndexRoute
  '/$citySlug/admin/pages/': typeof CitySlugAdminPagesIndexRoute
  '/$citySlug/admin/social/': typeof CitySlugAdminSocialIndexRoute
  '/$citySlug/admin/tools/': typeof CitySlugAdminToolsIndexRoute
  '/$citySlug/community/learn/': typeof CitySlugCommunityLearnIndexRoute
  '/$citySlug/community/profile/': typeof CitySlugCommunityProfileIndexRoute
  '/$citySlug/events/$slug/': typeof CitySlugEventsSlugIndexRoute
  '/$citySlug/events/claude-impact-lab-melbourne/': typeof CitySlugEventsClaudeImpactLabMelbourneIndexRoute
  '/$citySlug/admin/courses/$id/edit': typeof CitySlugAdminCoursesIdEditRoute
  '/$citySlug/community/learn/$slug/$lesson': typeof CitySlugCommunityLearnSlugLessonRoute
  '/$citySlug/community/learn/$slug/': typeof CitySlugCommunityLearnSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/offline': typeof OfflineRoute
  '/pricing': typeof PricingRoute
  '/remotion': typeof RemotionRoute
  '/signup': typeof SignupRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/$citySlug/cowork': typeof CitySlugCoworkRoute
  '/$citySlug/membership': typeof CitySlugMembershipRoute
  '/$citySlug/merch': typeof CitySlugMerchRoute
  '/$citySlug/professionals': typeof CitySlugProfessionalsRoute
  '/$citySlug/vibe-coders': typeof CitySlugVibeCodersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/upload': typeof ApiUploadRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/signup/sso-callback': typeof SignupSsoCallbackRoute
  '/$citySlug': typeof CitySlugIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$citySlug/admin/analytics': typeof CitySlugAdminAnalyticsRoute
  '/$citySlug/admin/badges': typeof CitySlugAdminBadgesRoute
  '/$citySlug/admin/cities': typeof CitySlugAdminCitiesRoute
  '/$citySlug/admin/import': typeof CitySlugAdminImportRoute
  '/$citySlug/admin/invite': typeof CitySlugAdminInviteRoute
  '/$citySlug/admin/posts': typeof CitySlugAdminPostsRoute
  '/$citySlug/admin/roles': typeof CitySlugAdminRolesRoute
  '/$citySlug/admin/settings': typeof CitySlugAdminSettingsRoute
  '/$citySlug/admin/speakers': typeof CitySlugAdminSpeakersRoute
  '/$citySlug/admin/tiers': typeof CitySlugAdminTiersRoute
  '/$citySlug/admin/users': typeof CitySlugAdminUsersRoute
  '/$citySlug/cities/$slug': typeof CitySlugCitiesSlugRoute
  '/$citySlug/community/bookmarks': typeof CitySlugCommunityBookmarksRoute
  '/$citySlug/community/bug-report': typeof CitySlugCommunityBugReportRoute
  '/$citySlug/community/connections': typeof CitySlugCommunityConnectionsRoute
  '/$citySlug/community/events': typeof CitySlugCommunityEventsRoute
  '/$citySlug/community/guidelines': typeof CitySlugCommunityGuidelinesRoute
  '/$citySlug/community/leaderboard': typeof CitySlugCommunityLeaderboardRoute
  '/$citySlug/community/members': typeof CitySlugCommunityMembersRoute
  '/$citySlug/community/notifications': typeof CitySlugCommunityNotificationsRoute
  '/$citySlug/community/search': typeof CitySlugCommunitySearchRoute
  '/$citySlug/courses/$slug': typeof CitySlugCoursesSlugRoute
  '/$citySlug/for/$slug': typeof CitySlugForSlugRoute
  '/$citySlug/impact-lab/admin': typeof CitySlugImpactLabAdminRoute
  '/$citySlug/impact-lab/portal': typeof CitySlugImpactLabPortalRoute
  '/$citySlug/my-talks/$id': typeof CitySlugMyTalksIdRoute
  '/$citySlug/p/$': typeof CitySlugPSplatRoute
  '/$citySlug/resources/$slug': typeof CitySlugResourcesSlugRoute
  '/$citySlug/webinars/claude-code-webinar-australia': typeof CitySlugWebinarsClaudeCodeWebinarAustraliaRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/$citySlug/admin': typeof CitySlugAdminIndexRoute
  '/$citySlug/community': typeof CitySlugCommunityIndexRoute
  '/$citySlug/courses': typeof CitySlugCoursesIndexRoute
  '/$citySlug/events': typeof CitySlugEventsIndexRoute
  '/$citySlug/for': typeof CitySlugForIndexRoute
  '/$citySlug/impact-lab': typeof CitySlugImpactLabIndexRoute
  '/$citySlug/my-talks': typeof CitySlugMyTalksIndexRoute
  '/$citySlug/resources': typeof CitySlugResourcesIndexRoute
  '/$citySlug/speak': typeof CitySlugSpeakIndexRoute
  '/$citySlug/admin/courses/new': typeof CitySlugAdminCoursesNewRoute
  '/$citySlug/admin/email/$id': typeof CitySlugAdminEmailIdRoute
  '/$citySlug/admin/email/analytics': typeof CitySlugAdminEmailAnalyticsRoute
  '/$citySlug/admin/email/automations': typeof CitySlugAdminEmailAutomationsRoute
  '/$citySlug/admin/email/contacts': typeof CitySlugAdminEmailContactsRoute
  '/$citySlug/admin/email/new': typeof CitySlugAdminEmailNewRoute
  '/$citySlug/admin/email/settings': typeof CitySlugAdminEmailSettingsRoute
  '/$citySlug/admin/email/templates': typeof CitySlugAdminEmailTemplatesRoute
  '/$citySlug/admin/events/new': typeof CitySlugAdminEventsNewRoute
  '/$citySlug/admin/industries/$slug': typeof CitySlugAdminIndustriesSlugRoute
  '/$citySlug/admin/industries/new': typeof CitySlugAdminIndustriesNewRoute
  '/$citySlug/admin/pages/$id': typeof CitySlugAdminPagesIdRoute
  '/$citySlug/admin/pages/home': typeof CitySlugAdminPagesHomeRoute
  '/$citySlug/admin/pages/new': typeof CitySlugAdminPagesNewRoute
  '/$citySlug/admin/social/settings': typeof CitySlugAdminSocialSettingsRoute
  '/$citySlug/admin/tools/attendance-planner': typeof CitySlugAdminToolsAttendancePlannerRoute
  '/$citySlug/admin/tools/attendee-analytics': typeof CitySlugAdminToolsAttendeeAnalyticsRoute
  '/$citySlug/admin/tools/qr-generator': typeof CitySlugAdminToolsQrGeneratorRoute
  '/$citySlug/admin/tools/slide-generator': typeof CitySlugAdminToolsSlideGeneratorRoute
  '/$citySlug/community/posts/$id': typeof CitySlugCommunityPostsIdRoute
  '/$citySlug/community/profile/$id': typeof CitySlugCommunityProfileIdRoute
  '/$citySlug/community/settings/notifications': typeof CitySlugCommunitySettingsNotificationsRoute
  '/$citySlug/community/settings/profile': typeof CitySlugCommunitySettingsProfileRoute
  '/$citySlug/events/$slug/resources': typeof CitySlugEventsSlugResourcesRoute
  '/$citySlug/events/claude-impact-lab-melbourne/sponsor': typeof CitySlugEventsClaudeImpactLabMelbourneSponsorRoute
  '/$citySlug/admin/courses': typeof CitySlugAdminCoursesIndexRoute
  '/$citySlug/admin/email': typeof CitySlugAdminEmailIndexRoute
  '/$citySlug/admin/events': typeof CitySlugAdminEventsIndexRoute
  '/$citySlug/admin/industries': typeof CitySlugAdminIndustriesIndexRoute
  '/$citySlug/admin/pages': typeof CitySlugAdminPagesIndexRoute
  '/$citySlug/admin/social': typeof CitySlugAdminSocialIndexRoute
  '/$citySlug/admin/tools': typeof CitySlugAdminToolsIndexRoute
  '/$citySlug/community/learn': typeof CitySlugCommunityLearnIndexRoute
  '/$citySlug/community/profile': typeof CitySlugCommunityProfileIndexRoute
  '/$citySlug/events/$slug': typeof CitySlugEventsSlugIndexRoute
  '/$citySlug/events/claude-impact-lab-melbourne': typeof CitySlugEventsClaudeImpactLabMelbourneIndexRoute
  '/$citySlug/admin/courses/$id/edit': typeof CitySlugAdminCoursesIdEditRoute
  '/$citySlug/community/learn/$slug/$lesson': typeof CitySlugCommunityLearnSlugLessonRoute
  '/$citySlug/community/learn/$slug': typeof CitySlugCommunityLearnSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRouteRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/offline': typeof OfflineRoute
  '/pricing': typeof PricingRoute
  '/remotion': typeof RemotionRoute
  '/signup': typeof SignupRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/$citySlug/admin': typeof CitySlugAdminRouteRouteWithChildren
  '/$citySlug/community': typeof CitySlugCommunityRouteRouteWithChildren
  '/$citySlug/cowork': typeof CitySlugCoworkRoute
  '/$citySlug/membership': typeof CitySlugMembershipRoute
  '/$citySlug/merch': typeof CitySlugMerchRoute
  '/$citySlug/professionals': typeof CitySlugProfessionalsRoute
  '/$citySlug/vibe-coders': typeof CitySlugVibeCodersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/upload': typeof ApiUploadRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/signup/sso-callback': typeof SignupSsoCallbackRoute
  '/$citySlug/': typeof CitySlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$citySlug/admin/analytics': typeof CitySlugAdminAnalyticsRoute
  '/$citySlug/admin/badges': typeof CitySlugAdminBadgesRoute
  '/$citySlug/admin/cities': typeof CitySlugAdminCitiesRoute
  '/$citySlug/admin/import': typeof CitySlugAdminImportRoute
  '/$citySlug/admin/invite': typeof CitySlugAdminInviteRoute
  '/$citySlug/admin/posts': typeof CitySlugAdminPostsRoute
  '/$citySlug/admin/roles': typeof CitySlugAdminRolesRoute
  '/$citySlug/admin/settings': typeof CitySlugAdminSettingsRoute
  '/$citySlug/admin/speakers': typeof CitySlugAdminSpeakersRoute
  '/$citySlug/admin/tiers': typeof CitySlugAdminTiersRoute
  '/$citySlug/admin/users': typeof CitySlugAdminUsersRoute
  '/$citySlug/cities/$slug': typeof CitySlugCitiesSlugRoute
  '/$citySlug/community/bookmarks': typeof CitySlugCommunityBookmarksRoute
  '/$citySlug/community/bug-report': typeof CitySlugCommunityBugReportRoute
  '/$citySlug/community/connections': typeof CitySlugCommunityConnectionsRoute
  '/$citySlug/community/events': typeof CitySlugCommunityEventsRoute
  '/$citySlug/community/guidelines': typeof CitySlugCommunityGuidelinesRoute
  '/$citySlug/community/leaderboard': typeof CitySlugCommunityLeaderboardRoute
  '/$citySlug/community/members': typeof CitySlugCommunityMembersRoute
  '/$citySlug/community/notifications': typeof CitySlugCommunityNotificationsRoute
  '/$citySlug/community/search': typeof CitySlugCommunitySearchRoute
  '/$citySlug/courses/$slug': typeof CitySlugCoursesSlugRoute
  '/$citySlug/for/$slug': typeof CitySlugForSlugRoute
  '/$citySlug/impact-lab/admin': typeof CitySlugImpactLabAdminRoute
  '/$citySlug/impact-lab/portal': typeof CitySlugImpactLabPortalRoute
  '/$citySlug/my-talks/$id': typeof CitySlugMyTalksIdRoute
  '/$citySlug/p/$': typeof CitySlugPSplatRoute
  '/$citySlug/resources/$slug': typeof CitySlugResourcesSlugRoute
  '/$citySlug/webinars/claude-code-webinar-australia': typeof CitySlugWebinarsClaudeCodeWebinarAustraliaRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/$citySlug/admin/': typeof CitySlugAdminIndexRoute
  '/$citySlug/community/': typeof CitySlugCommunityIndexRoute
  '/$citySlug/courses/': typeof CitySlugCoursesIndexRoute
  '/$citySlug/events/': typeof CitySlugEventsIndexRoute
  '/$citySlug/for/': typeof CitySlugForIndexRoute
  '/$citySlug/impact-lab/': typeof CitySlugImpactLabIndexRoute
  '/$citySlug/my-talks/': typeof CitySlugMyTalksIndexRoute
  '/$citySlug/resources/': typeof CitySlugResourcesIndexRoute
  '/$citySlug/speak/': typeof CitySlugSpeakIndexRoute
  '/$citySlug/admin/courses/new': typeof CitySlugAdminCoursesNewRoute
  '/$citySlug/admin/email/$id': typeof CitySlugAdminEmailIdRoute
  '/$citySlug/admin/email/analytics': typeof CitySlugAdminEmailAnalyticsRoute
  '/$citySlug/admin/email/automations': typeof CitySlugAdminEmailAutomationsRoute
  '/$citySlug/admin/email/contacts': typeof CitySlugAdminEmailContactsRoute
  '/$citySlug/admin/email/new': typeof CitySlugAdminEmailNewRoute
  '/$citySlug/admin/email/settings': typeof CitySlugAdminEmailSettingsRoute
  '/$citySlug/admin/email/templates': typeof CitySlugAdminEmailTemplatesRoute
  '/$citySlug/admin/events/new': typeof CitySlugAdminEventsNewRoute
  '/$citySlug/admin/industries/$slug': typeof CitySlugAdminIndustriesSlugRoute
  '/$citySlug/admin/industries/new': typeof CitySlugAdminIndustriesNewRoute
  '/$citySlug/admin/pages/$id': typeof CitySlugAdminPagesIdRoute
  '/$citySlug/admin/pages/home': typeof CitySlugAdminPagesHomeRoute
  '/$citySlug/admin/pages/new': typeof CitySlugAdminPagesNewRoute
  '/$citySlug/admin/social/settings': typeof CitySlugAdminSocialSettingsRoute
  '/$citySlug/admin/tools/attendance-planner': typeof CitySlugAdminToolsAttendancePlannerRoute
  '/$citySlug/admin/tools/attendee-analytics': typeof CitySlugAdminToolsAttendeeAnalyticsRoute
  '/$citySlug/admin/tools/qr-generator': typeof CitySlugAdminToolsQrGeneratorRoute
  '/$citySlug/admin/tools/slide-generator': typeof CitySlugAdminToolsSlideGeneratorRoute
  '/$citySlug/community/posts/$id': typeof CitySlugCommunityPostsIdRoute
  '/$citySlug/community/profile/$id': typeof CitySlugCommunityProfileIdRoute
  '/$citySlug/community/settings/notifications': typeof CitySlugCommunitySettingsNotificationsRoute
  '/$citySlug/community/settings/profile': typeof CitySlugCommunitySettingsProfileRoute
  '/$citySlug/events/$slug/resources': typeof CitySlugEventsSlugResourcesRoute
  '/$citySlug/events/claude-impact-lab-melbourne/sponsor': typeof CitySlugEventsClaudeImpactLabMelbourneSponsorRoute
  '/$citySlug/admin/courses/': typeof CitySlugAdminCoursesIndexRoute
  '/$citySlug/admin/email/': typeof CitySlugAdminEmailIndexRoute
  '/$citySlug/admin/events/': typeof CitySlugAdminEventsIndexRoute
  '/$citySlug/admin/industries/': typeof CitySlugAdminIndustriesIndexRoute
  '/$citySlug/admin/pages/': typeof CitySlugAdminPagesIndexRoute
  '/$citySlug/admin/social/': typeof CitySlugAdminSocialIndexRoute
  '/$citySlug/admin/tools/': typeof CitySlugAdminToolsIndexRoute
  '/$citySlug/community/learn/': typeof CitySlugCommunityLearnIndexRoute
  '/$citySlug/community/profile/': typeof CitySlugCommunityProfileIndexRoute
  '/$citySlug/events/$slug/': typeof CitySlugEventsSlugIndexRoute
  '/$citySlug/events/claude-impact-lab-melbourne/': typeof CitySlugEventsClaudeImpactLabMelbourneIndexRoute
  '/$citySlug/admin/courses/$id/edit': typeof CitySlugAdminCoursesIdEditRoute
  '/$citySlug/community/learn/$slug/$lesson': typeof CitySlugCommunityLearnSlugLessonRoute
  '/$citySlug/community/learn/$slug/': typeof CitySlugCommunityLearnSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$citySlug'
    | '/login'
    | '/offline'
    | '/pricing'
    | '/remotion'
    | '/signup'
    | '/sitemap'
    | '/$citySlug/admin'
    | '/$citySlug/community'
    | '/$citySlug/cowork'
    | '/$citySlug/membership'
    | '/$citySlug/merch'
    | '/$citySlug/professionals'
    | '/$citySlug/vibe-coders'
    | '/api/health'
    | '/api/mcp'
    | '/api/upload'
    | '/login/sso-callback'
    | '/signup/sso-callback'
    | '/$citySlug/'
    | '/admin/'
    | '/$citySlug/admin/analytics'
    | '/$citySlug/admin/badges'
    | '/$citySlug/admin/cities'
    | '/$citySlug/admin/import'
    | '/$citySlug/admin/invite'
    | '/$citySlug/admin/posts'
    | '/$citySlug/admin/roles'
    | '/$citySlug/admin/settings'
    | '/$citySlug/admin/speakers'
    | '/$citySlug/admin/tiers'
    | '/$citySlug/admin/users'
    | '/$citySlug/cities/$slug'
    | '/$citySlug/community/bookmarks'
    | '/$citySlug/community/bug-report'
    | '/$citySlug/community/connections'
    | '/$citySlug/community/events'
    | '/$citySlug/community/guidelines'
    | '/$citySlug/community/leaderboard'
    | '/$citySlug/community/members'
    | '/$citySlug/community/notifications'
    | '/$citySlug/community/search'
    | '/$citySlug/courses/$slug'
    | '/$citySlug/for/$slug'
    | '/$citySlug/impact-lab/admin'
    | '/$citySlug/impact-lab/portal'
    | '/$citySlug/my-talks/$id'
    | '/$citySlug/p/$'
    | '/$citySlug/resources/$slug'
    | '/$citySlug/webinars/claude-code-webinar-australia'
    | '/api/files/$'
    | '/$citySlug/admin/'
    | '/$citySlug/community/'
    | '/$citySlug/courses/'
    | '/$citySlug/events/'
    | '/$citySlug/for/'
    | '/$citySlug/impact-lab/'
    | '/$citySlug/my-talks/'
    | '/$citySlug/resources/'
    | '/$citySlug/speak/'
    | '/$citySlug/admin/courses/new'
    | '/$citySlug/admin/email/$id'
    | '/$citySlug/admin/email/analytics'
    | '/$citySlug/admin/email/automations'
    | '/$citySlug/admin/email/contacts'
    | '/$citySlug/admin/email/new'
    | '/$citySlug/admin/email/settings'
    | '/$citySlug/admin/email/templates'
    | '/$citySlug/admin/events/new'
    | '/$citySlug/admin/industries/$slug'
    | '/$citySlug/admin/industries/new'
    | '/$citySlug/admin/pages/$id'
    | '/$citySlug/admin/pages/home'
    | '/$citySlug/admin/pages/new'
    | '/$citySlug/admin/social/settings'
    | '/$citySlug/admin/tools/attendance-planner'
    | '/$citySlug/admin/tools/attendee-analytics'
    | '/$citySlug/admin/tools/qr-generator'
    | '/$citySlug/admin/tools/slide-generator'
    | '/$citySlug/community/posts/$id'
    | '/$citySlug/community/profile/$id'
    | '/$citySlug/community/settings/notifications'
    | '/$citySlug/community/settings/profile'
    | '/$citySlug/events/$slug/resources'
    | '/$citySlug/events/claude-impact-lab-melbourne/sponsor'
    | '/$citySlug/admin/courses/'
    | '/$citySlug/admin/email/'
    | '/$citySlug/admin/events/'
    | '/$citySlug/admin/industries/'
    | '/$citySlug/admin/pages/'
    | '/$citySlug/admin/social/'
    | '/$citySlug/admin/tools/'
    | '/$citySlug/community/learn/'
    | '/$citySlug/community/profile/'
    | '/$citySlug/events/$slug/'
    | '/$citySlug/events/claude-impact-lab-melbourne/'
    | '/$citySlug/admin/courses/$id/edit'
    | '/$citySlug/community/learn/$slug/$lesson'
    | '/$citySlug/community/learn/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/offline'
    | '/pricing'
    | '/remotion'
    | '/signup'
    | '/sitemap'
    | '/$citySlug/cowork'
    | '/$citySlug/membership'
    | '/$citySlug/merch'
    | '/$citySlug/professionals'
    | '/$citySlug/vibe-coders'
    | '/api/health'
    | '/api/mcp'
    | '/api/upload'
    | '/login/sso-callback'
    | '/signup/sso-callback'
    | '/$citySlug'
    | '/admin'
    | '/$citySlug/admin/analytics'
    | '/$citySlug/admin/badges'
    | '/$citySlug/admin/cities'
    | '/$citySlug/admin/import'
    | '/$citySlug/admin/invite'
    | '/$citySlug/admin/posts'
    | '/$citySlug/admin/roles'
    | '/$citySlug/admin/settings'
    | '/$citySlug/admin/speakers'
    | '/$citySlug/admin/tiers'
    | '/$citySlug/admin/users'
    | '/$citySlug/cities/$slug'
    | '/$citySlug/community/bookmarks'
    | '/$citySlug/community/bug-report'
    | '/$citySlug/community/connections'
    | '/$citySlug/community/events'
    | '/$citySlug/community/guidelines'
    | '/$citySlug/community/leaderboard'
    | '/$citySlug/community/members'
    | '/$citySlug/community/notifications'
    | '/$citySlug/community/search'
    | '/$citySlug/courses/$slug'
    | '/$citySlug/for/$slug'
    | '/$citySlug/impact-lab/admin'
    | '/$citySlug/impact-lab/portal'
    | '/$citySlug/my-talks/$id'
    | '/$citySlug/p/$'
    | '/$citySlug/resources/$slug'
    | '/$citySlug/webinars/claude-code-webinar-australia'
    | '/api/files/$'
    | '/$citySlug/admin'
    | '/$citySlug/community'
    | '/$citySlug/courses'
    | '/$citySlug/events'
    | '/$citySlug/for'
    | '/$citySlug/impact-lab'
    | '/$citySlug/my-talks'
    | '/$citySlug/resources'
    | '/$citySlug/speak'
    | '/$citySlug/admin/courses/new'
    | '/$citySlug/admin/email/$id'
    | '/$citySlug/admin/email/analytics'
    | '/$citySlug/admin/email/automations'
    | '/$citySlug/admin/email/contacts'
    | '/$citySlug/admin/email/new'
    | '/$citySlug/admin/email/settings'
    | '/$citySlug/admin/email/templates'
    | '/$citySlug/admin/events/new'
    | '/$citySlug/admin/industries/$slug'
    | '/$citySlug/admin/industries/new'
    | '/$citySlug/admin/pages/$id'
    | '/$citySlug/admin/pages/home'
    | '/$citySlug/admin/pages/new'
    | '/$citySlug/admin/social/settings'
    | '/$citySlug/admin/tools/attendance-planner'
    | '/$citySlug/admin/tools/attendee-analytics'
    | '/$citySlug/admin/tools/qr-generator'
    | '/$citySlug/admin/tools/slide-generator'
    | '/$citySlug/community/posts/$id'
    | '/$citySlug/community/profile/$id'
    | '/$citySlug/community/settings/notifications'
    | '/$citySlug/community/settings/profile'
    | '/$citySlug/events/$slug/resources'
    | '/$citySlug/events/claude-impact-lab-melbourne/sponsor'
    | '/$citySlug/admin/courses'
    | '/$citySlug/admin/email'
    | '/$citySlug/admin/events'
    | '/$citySlug/admin/industries'
    | '/$citySlug/admin/pages'
    | '/$citySlug/admin/social'
    | '/$citySlug/admin/tools'
    | '/$citySlug/community/learn'
    | '/$citySlug/community/profile'
    | '/$citySlug/events/$slug'
    | '/$citySlug/events/claude-impact-lab-melbourne'
    | '/$citySlug/admin/courses/$id/edit'
    | '/$citySlug/community/learn/$slug/$lesson'
    | '/$citySlug/community/learn/$slug'
  id:
    | '__root__'
    | '/'
    | '/$citySlug'
    | '/login'
    | '/offline'
    | '/pricing'
    | '/remotion'
    | '/signup'
    | '/sitemap'
    | '/$citySlug/admin'
    | '/$citySlug/community'
    | '/$citySlug/cowork'
    | '/$citySlug/membership'
    | '/$citySlug/merch'
    | '/$citySlug/professionals'
    | '/$citySlug/vibe-coders'
    | '/api/health'
    | '/api/mcp'
    | '/api/upload'
    | '/login/sso-callback'
    | '/signup/sso-callback'
    | '/$citySlug/'
    | '/admin/'
    | '/$citySlug/admin/analytics'
    | '/$citySlug/admin/badges'
    | '/$citySlug/admin/cities'
    | '/$citySlug/admin/import'
    | '/$citySlug/admin/invite'
    | '/$citySlug/admin/posts'
    | '/$citySlug/admin/roles'
    | '/$citySlug/admin/settings'
    | '/$citySlug/admin/speakers'
    | '/$citySlug/admin/tiers'
    | '/$citySlug/admin/users'
    | '/$citySlug/cities/$slug'
    | '/$citySlug/community/bookmarks'
    | '/$citySlug/community/bug-report'
    | '/$citySlug/community/connections'
    | '/$citySlug/community/events'
    | '/$citySlug/community/guidelines'
    | '/$citySlug/community/leaderboard'
    | '/$citySlug/community/members'
    | '/$citySlug/community/notifications'
    | '/$citySlug/community/search'
    | '/$citySlug/courses/$slug'
    | '/$citySlug/for/$slug'
    | '/$citySlug/impact-lab/admin'
    | '/$citySlug/impact-lab/portal'
    | '/$citySlug/my-talks/$id'
    | '/$citySlug/p/$'
    | '/$citySlug/resources/$slug'
    | '/$citySlug/webinars/claude-code-webinar-australia'
    | '/api/files/$'
    | '/$citySlug/admin/'
    | '/$citySlug/community/'
    | '/$citySlug/courses/'
    | '/$citySlug/events/'
    | '/$citySlug/for/'
    | '/$citySlug/impact-lab/'
    | '/$citySlug/my-talks/'
    | '/$citySlug/resources/'
    | '/$citySlug/speak/'
    | '/$citySlug/admin/courses/new'
    | '/$citySlug/admin/email/$id'
    | '/$citySlug/admin/email/analytics'
    | '/$citySlug/admin/email/automations'
    | '/$citySlug/admin/email/contacts'
    | '/$citySlug/admin/email/new'
    | '/$citySlug/admin/email/settings'
    | '/$citySlug/admin/email/templates'
    | '/$citySlug/admin/events/new'
    | '/$citySlug/admin/industries/$slug'
    | '/$citySlug/admin/industries/new'
    | '/$citySlug/admin/pages/$id'
    | '/$citySlug/admin/pages/home'
    | '/$citySlug/admin/pages/new'
    | '/$citySlug/admin/social/settings'
    | '/$citySlug/admin/tools/attendance-planner'
    | '/$citySlug/admin/tools/attendee-analytics'
    | '/$citySlug/admin/tools/qr-generator'
    | '/$citySlug/admin/tools/slide-generator'
    | '/$citySlug/community/posts/$id'
    | '/$citySlug/community/profile/$id'
    | '/$citySlug/community/settings/notifications'
    | '/$citySlug/community/settings/profile'
    | '/$citySlug/events/$slug/resources'
    | '/$citySlug/events/claude-impact-lab-melbourne/sponsor'
    | '/$citySlug/admin/courses/'
    | '/$citySlug/admin/email/'
    | '/$citySlug/admin/events/'
    | '/$citySlug/admin/industries/'
    | '/$citySlug/admin/pages/'
    | '/$citySlug/admin/social/'
    | '/$citySlug/admin/tools/'
    | '/$citySlug/community/learn/'
    | '/$citySlug/community/profile/'
    | '/$citySlug/events/$slug/'
    | '/$citySlug/events/claude-impact-lab-melbourne/'
    | '/$citySlug/admin/courses/$id/edit'
    | '/$citySlug/community/learn/$slug/$lesson'
    | '/$citySlug/community/learn/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitySlugRouteRoute: typeof CitySlugRouteRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  PricingRoute: typeof PricingRoute
  RemotionRoute: typeof RemotionRoute
  SignupRoute: typeof SignupRouteWithChildren
  SitemapRoute: typeof SitemapRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiUploadRoute: typeof ApiUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$citySlug': {
      id: '/$citySlug'
      path: '/$citySlug'
      fullPath: '/$citySlug'
      preLoaderRoute: typeof CitySlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remotion': {
      id: '/remotion'
      path: '/remotion'
      fullPath: '/remotion'
      preLoaderRoute: typeof RemotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$citySlug/': {
      id: '/$citySlug/'
      path: '/'
      fullPath: '/$citySlug/'
      preLoaderRoute: typeof CitySlugIndexRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/admin': {
      id: '/$citySlug/admin'
      path: '/admin'
      fullPath: '/$citySlug/admin'
      preLoaderRoute: typeof CitySlugAdminRouteRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/community': {
      id: '/$citySlug/community'
      path: '/community'
      fullPath: '/$citySlug/community'
      preLoaderRoute: typeof CitySlugCommunityRouteRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/cowork': {
      id: '/$citySlug/cowork'
      path: '/cowork'
      fullPath: '/$citySlug/cowork'
      preLoaderRoute: typeof CitySlugCoworkRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/membership': {
      id: '/$citySlug/membership'
      path: '/membership'
      fullPath: '/$citySlug/membership'
      preLoaderRoute: typeof CitySlugMembershipRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/merch': {
      id: '/$citySlug/merch'
      path: '/merch'
      fullPath: '/$citySlug/merch'
      preLoaderRoute: typeof CitySlugMerchRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/professionals': {
      id: '/$citySlug/professionals'
      path: '/professionals'
      fullPath: '/$citySlug/professionals'
      preLoaderRoute: typeof CitySlugProfessionalsRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/vibe-coders': {
      id: '/$citySlug/vibe-coders'
      path: '/vibe-coders'
      fullPath: '/$citySlug/vibe-coders'
      preLoaderRoute: typeof CitySlugVibeCodersRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/sso-callback': {
      id: '/login/sso-callback'
      path: '/sso-callback'
      fullPath: '/login/sso-callback'
      preLoaderRoute: typeof LoginSsoCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/signup/sso-callback': {
      id: '/signup/sso-callback'
      path: '/sso-callback'
      fullPath: '/signup/sso-callback'
      preLoaderRoute: typeof SignupSsoCallbackRouteImport
      parentRoute: typeof SignupRoute
    }
    '/$citySlug/admin/': {
      id: '/$citySlug/admin/'
      path: '/'
      fullPath: '/$citySlug/admin/'
      preLoaderRoute: typeof CitySlugAdminIndexRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/analytics': {
      id: '/$citySlug/admin/analytics'
      path: '/analytics'
      fullPath: '/$citySlug/admin/analytics'
      preLoaderRoute: typeof CitySlugAdminAnalyticsRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/badges': {
      id: '/$citySlug/admin/badges'
      path: '/badges'
      fullPath: '/$citySlug/admin/badges'
      preLoaderRoute: typeof CitySlugAdminBadgesRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/cities': {
      id: '/$citySlug/admin/cities'
      path: '/cities'
      fullPath: '/$citySlug/admin/cities'
      preLoaderRoute: typeof CitySlugAdminCitiesRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/import': {
      id: '/$citySlug/admin/import'
      path: '/import'
      fullPath: '/$citySlug/admin/import'
      preLoaderRoute: typeof CitySlugAdminImportRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/invite': {
      id: '/$citySlug/admin/invite'
      path: '/invite'
      fullPath: '/$citySlug/admin/invite'
      preLoaderRoute: typeof CitySlugAdminInviteRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/posts': {
      id: '/$citySlug/admin/posts'
      path: '/posts'
      fullPath: '/$citySlug/admin/posts'
      preLoaderRoute: typeof CitySlugAdminPostsRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/roles': {
      id: '/$citySlug/admin/roles'
      path: '/roles'
      fullPath: '/$citySlug/admin/roles'
      preLoaderRoute: typeof CitySlugAdminRolesRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/settings': {
      id: '/$citySlug/admin/settings'
      path: '/settings'
      fullPath: '/$citySlug/admin/settings'
      preLoaderRoute: typeof CitySlugAdminSettingsRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/speakers': {
      id: '/$citySlug/admin/speakers'
      path: '/speakers'
      fullPath: '/$citySlug/admin/speakers'
      preLoaderRoute: typeof CitySlugAdminSpeakersRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/tiers': {
      id: '/$citySlug/admin/tiers'
      path: '/tiers'
      fullPath: '/$citySlug/admin/tiers'
      preLoaderRoute: typeof CitySlugAdminTiersRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/users': {
      id: '/$citySlug/admin/users'
      path: '/users'
      fullPath: '/$citySlug/admin/users'
      preLoaderRoute: typeof CitySlugAdminUsersRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/cities/$slug': {
      id: '/$citySlug/cities/$slug'
      path: '/cities/$slug'
      fullPath: '/$citySlug/cities/$slug'
      preLoaderRoute: typeof CitySlugCitiesSlugRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/community/': {
      id: '/$citySlug/community/'
      path: '/'
      fullPath: '/$citySlug/community/'
      preLoaderRoute: typeof CitySlugCommunityIndexRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/bookmarks': {
      id: '/$citySlug/community/bookmarks'
      path: '/bookmarks'
      fullPath: '/$citySlug/community/bookmarks'
      preLoaderRoute: typeof CitySlugCommunityBookmarksRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/bug-report': {
      id: '/$citySlug/community/bug-report'
      path: '/bug-report'
      fullPath: '/$citySlug/community/bug-report'
      preLoaderRoute: typeof CitySlugCommunityBugReportRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/connections': {
      id: '/$citySlug/community/connections'
      path: '/connections'
      fullPath: '/$citySlug/community/connections'
      preLoaderRoute: typeof CitySlugCommunityConnectionsRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/events': {
      id: '/$citySlug/community/events'
      path: '/events'
      fullPath: '/$citySlug/community/events'
      preLoaderRoute: typeof CitySlugCommunityEventsRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/guidelines': {
      id: '/$citySlug/community/guidelines'
      path: '/guidelines'
      fullPath: '/$citySlug/community/guidelines'
      preLoaderRoute: typeof CitySlugCommunityGuidelinesRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/leaderboard': {
      id: '/$citySlug/community/leaderboard'
      path: '/leaderboard'
      fullPath: '/$citySlug/community/leaderboard'
      preLoaderRoute: typeof CitySlugCommunityLeaderboardRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/members': {
      id: '/$citySlug/community/members'
      path: '/members'
      fullPath: '/$citySlug/community/members'
      preLoaderRoute: typeof CitySlugCommunityMembersRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/notifications': {
      id: '/$citySlug/community/notifications'
      path: '/notifications'
      fullPath: '/$citySlug/community/notifications'
      preLoaderRoute: typeof CitySlugCommunityNotificationsRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/search': {
      id: '/$citySlug/community/search'
      path: '/search'
      fullPath: '/$citySlug/community/search'
      preLoaderRoute: typeof CitySlugCommunitySearchRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/courses/': {
      id: '/$citySlug/courses/'
      path: '/courses'
      fullPath: '/$citySlug/courses/'
      preLoaderRoute: typeof CitySlugCoursesIndexRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/courses/$slug': {
      id: '/$citySlug/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/$citySlug/courses/$slug'
      preLoaderRoute: typeof CitySlugCoursesSlugRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/events/': {
      id: '/$citySlug/events/'
      path: '/events'
      fullPath: '/$citySlug/events/'
      preLoaderRoute: typeof CitySlugEventsIndexRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/for/': {
      id: '/$citySlug/for/'
      path: '/for'
      fullPath: '/$citySlug/for/'
      preLoaderRoute: typeof CitySlugForIndexRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/for/$slug': {
      id: '/$citySlug/for/$slug'
      path: '/for/$slug'
      fullPath: '/$citySlug/for/$slug'
      preLoaderRoute: typeof CitySlugForSlugRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/impact-lab/': {
      id: '/$citySlug/impact-lab/'
      path: '/impact-lab'
      fullPath: '/$citySlug/impact-lab/'
      preLoaderRoute: typeof CitySlugImpactLabIndexRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/impact-lab/admin': {
      id: '/$citySlug/impact-lab/admin'
      path: '/impact-lab/admin'
      fullPath: '/$citySlug/impact-lab/admin'
      preLoaderRoute: typeof CitySlugImpactLabAdminRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/impact-lab/portal': {
      id: '/$citySlug/impact-lab/portal'
      path: '/impact-lab/portal'
      fullPath: '/$citySlug/impact-lab/portal'
      preLoaderRoute: typeof CitySlugImpactLabPortalRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/my-talks/': {
      id: '/$citySlug/my-talks/'
      path: '/my-talks'
      fullPath: '/$citySlug/my-talks/'
      preLoaderRoute: typeof CitySlugMyTalksIndexRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/my-talks/$id': {
      id: '/$citySlug/my-talks/$id'
      path: '/my-talks/$id'
      fullPath: '/$citySlug/my-talks/$id'
      preLoaderRoute: typeof CitySlugMyTalksIdRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/p/$': {
      id: '/$citySlug/p/$'
      path: '/p/$'
      fullPath: '/$citySlug/p/$'
      preLoaderRoute: typeof CitySlugPSplatRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/resources/': {
      id: '/$citySlug/resources/'
      path: '/resources'
      fullPath: '/$citySlug/resources/'
      preLoaderRoute: typeof CitySlugResourcesIndexRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/resources/$slug': {
      id: '/$citySlug/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/$citySlug/resources/$slug'
      preLoaderRoute: typeof CitySlugResourcesSlugRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/speak/': {
      id: '/$citySlug/speak/'
      path: '/speak'
      fullPath: '/$citySlug/speak/'
      preLoaderRoute: typeof CitySlugSpeakIndexRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/webinars/claude-code-webinar-australia': {
      id: '/$citySlug/webinars/claude-code-webinar-australia'
      path: '/webinars/claude-code-webinar-australia'
      fullPath: '/$citySlug/webinars/claude-code-webinar-australia'
      preLoaderRoute: typeof CitySlugWebinarsClaudeCodeWebinarAustraliaRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$citySlug/admin/courses/': {
      id: '/$citySlug/admin/courses/'
      path: '/courses'
      fullPath: '/$citySlug/admin/courses/'
      preLoaderRoute: typeof CitySlugAdminCoursesIndexRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/courses/new': {
      id: '/$citySlug/admin/courses/new'
      path: '/courses/new'
      fullPath: '/$citySlug/admin/courses/new'
      preLoaderRoute: typeof CitySlugAdminCoursesNewRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/email/': {
      id: '/$citySlug/admin/email/'
      path: '/email'
      fullPath: '/$citySlug/admin/email/'
      preLoaderRoute: typeof CitySlugAdminEmailIndexRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/email/$id': {
      id: '/$citySlug/admin/email/$id'
      path: '/email/$id'
      fullPath: '/$citySlug/admin/email/$id'
      preLoaderRoute: typeof CitySlugAdminEmailIdRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/email/analytics': {
      id: '/$citySlug/admin/email/analytics'
      path: '/email/analytics'
      fullPath: '/$citySlug/admin/email/analytics'
      preLoaderRoute: typeof CitySlugAdminEmailAnalyticsRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/email/automations': {
      id: '/$citySlug/admin/email/automations'
      path: '/email/automations'
      fullPath: '/$citySlug/admin/email/automations'
      preLoaderRoute: typeof CitySlugAdminEmailAutomationsRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/email/contacts': {
      id: '/$citySlug/admin/email/contacts'
      path: '/email/contacts'
      fullPath: '/$citySlug/admin/email/contacts'
      preLoaderRoute: typeof CitySlugAdminEmailContactsRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/email/new': {
      id: '/$citySlug/admin/email/new'
      path: '/email/new'
      fullPath: '/$citySlug/admin/email/new'
      preLoaderRoute: typeof CitySlugAdminEmailNewRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/email/settings': {
      id: '/$citySlug/admin/email/settings'
      path: '/email/settings'
      fullPath: '/$citySlug/admin/email/settings'
      preLoaderRoute: typeof CitySlugAdminEmailSettingsRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/email/templates': {
      id: '/$citySlug/admin/email/templates'
      path: '/email/templates'
      fullPath: '/$citySlug/admin/email/templates'
      preLoaderRoute: typeof CitySlugAdminEmailTemplatesRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/events/': {
      id: '/$citySlug/admin/events/'
      path: '/events'
      fullPath: '/$citySlug/admin/events/'
      preLoaderRoute: typeof CitySlugAdminEventsIndexRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/events/new': {
      id: '/$citySlug/admin/events/new'
      path: '/events/new'
      fullPath: '/$citySlug/admin/events/new'
      preLoaderRoute: typeof CitySlugAdminEventsNewRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/industries/': {
      id: '/$citySlug/admin/industries/'
      path: '/industries'
      fullPath: '/$citySlug/admin/industries/'
      preLoaderRoute: typeof CitySlugAdminIndustriesIndexRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/industries/$slug': {
      id: '/$citySlug/admin/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/$citySlug/admin/industries/$slug'
      preLoaderRoute: typeof CitySlugAdminIndustriesSlugRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/industries/new': {
      id: '/$citySlug/admin/industries/new'
      path: '/industries/new'
      fullPath: '/$citySlug/admin/industries/new'
      preLoaderRoute: typeof CitySlugAdminIndustriesNewRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/pages/': {
      id: '/$citySlug/admin/pages/'
      path: '/pages'
      fullPath: '/$citySlug/admin/pages/'
      preLoaderRoute: typeof CitySlugAdminPagesIndexRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/pages/$id': {
      id: '/$citySlug/admin/pages/$id'
      path: '/pages/$id'
      fullPath: '/$citySlug/admin/pages/$id'
      preLoaderRoute: typeof CitySlugAdminPagesIdRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/pages/home': {
      id: '/$citySlug/admin/pages/home'
      path: '/pages/home'
      fullPath: '/$citySlug/admin/pages/home'
      preLoaderRoute: typeof CitySlugAdminPagesHomeRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/pages/new': {
      id: '/$citySlug/admin/pages/new'
      path: '/pages/new'
      fullPath: '/$citySlug/admin/pages/new'
      preLoaderRoute: typeof CitySlugAdminPagesNewRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/social/': {
      id: '/$citySlug/admin/social/'
      path: '/social'
      fullPath: '/$citySlug/admin/social/'
      preLoaderRoute: typeof CitySlugAdminSocialIndexRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/social/settings': {
      id: '/$citySlug/admin/social/settings'
      path: '/social/settings'
      fullPath: '/$citySlug/admin/social/settings'
      preLoaderRoute: typeof CitySlugAdminSocialSettingsRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/tools/': {
      id: '/$citySlug/admin/tools/'
      path: '/tools'
      fullPath: '/$citySlug/admin/tools/'
      preLoaderRoute: typeof CitySlugAdminToolsIndexRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/tools/attendance-planner': {
      id: '/$citySlug/admin/tools/attendance-planner'
      path: '/tools/attendance-planner'
      fullPath: '/$citySlug/admin/tools/attendance-planner'
      preLoaderRoute: typeof CitySlugAdminToolsAttendancePlannerRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/tools/attendee-analytics': {
      id: '/$citySlug/admin/tools/attendee-analytics'
      path: '/tools/attendee-analytics'
      fullPath: '/$citySlug/admin/tools/attendee-analytics'
      preLoaderRoute: typeof CitySlugAdminToolsAttendeeAnalyticsRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/tools/qr-generator': {
      id: '/$citySlug/admin/tools/qr-generator'
      path: '/tools/qr-generator'
      fullPath: '/$citySlug/admin/tools/qr-generator'
      preLoaderRoute: typeof CitySlugAdminToolsQrGeneratorRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/admin/tools/slide-generator': {
      id: '/$citySlug/admin/tools/slide-generator'
      path: '/tools/slide-generator'
      fullPath: '/$citySlug/admin/tools/slide-generator'
      preLoaderRoute: typeof CitySlugAdminToolsSlideGeneratorRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/community/learn/': {
      id: '/$citySlug/community/learn/'
      path: '/learn'
      fullPath: '/$citySlug/community/learn/'
      preLoaderRoute: typeof CitySlugCommunityLearnIndexRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/posts/$id': {
      id: '/$citySlug/community/posts/$id'
      path: '/posts/$id'
      fullPath: '/$citySlug/community/posts/$id'
      preLoaderRoute: typeof CitySlugCommunityPostsIdRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/profile/': {
      id: '/$citySlug/community/profile/'
      path: '/profile'
      fullPath: '/$citySlug/community/profile/'
      preLoaderRoute: typeof CitySlugCommunityProfileIndexRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/profile/$id': {
      id: '/$citySlug/community/profile/$id'
      path: '/profile/$id'
      fullPath: '/$citySlug/community/profile/$id'
      preLoaderRoute: typeof CitySlugCommunityProfileIdRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/settings/notifications': {
      id: '/$citySlug/community/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/$citySlug/community/settings/notifications'
      preLoaderRoute: typeof CitySlugCommunitySettingsNotificationsRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/settings/profile': {
      id: '/$citySlug/community/settings/profile'
      path: '/settings/profile'
      fullPath: '/$citySlug/community/settings/profile'
      preLoaderRoute: typeof CitySlugCommunitySettingsProfileRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/events/$slug/': {
      id: '/$citySlug/events/$slug/'
      path: '/events/$slug'
      fullPath: '/$citySlug/events/$slug/'
      preLoaderRoute: typeof CitySlugEventsSlugIndexRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/events/$slug/resources': {
      id: '/$citySlug/events/$slug/resources'
      path: '/events/$slug/resources'
      fullPath: '/$citySlug/events/$slug/resources'
      preLoaderRoute: typeof CitySlugEventsSlugResourcesRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/events/claude-impact-lab-melbourne/': {
      id: '/$citySlug/events/claude-impact-lab-melbourne/'
      path: '/events/claude-impact-lab-melbourne'
      fullPath: '/$citySlug/events/claude-impact-lab-melbourne/'
      preLoaderRoute: typeof CitySlugEventsClaudeImpactLabMelbourneIndexRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/events/claude-impact-lab-melbourne/sponsor': {
      id: '/$citySlug/events/claude-impact-lab-melbourne/sponsor'
      path: '/events/claude-impact-lab-melbourne/sponsor'
      fullPath: '/$citySlug/events/claude-impact-lab-melbourne/sponsor'
      preLoaderRoute: typeof CitySlugEventsClaudeImpactLabMelbourneSponsorRouteImport
      parentRoute: typeof CitySlugRouteRoute
    }
    '/$citySlug/admin/courses/$id/edit': {
      id: '/$citySlug/admin/courses/$id/edit'
      path: '/courses/$id/edit'
      fullPath: '/$citySlug/admin/courses/$id/edit'
      preLoaderRoute: typeof CitySlugAdminCoursesIdEditRouteImport
      parentRoute: typeof CitySlugAdminRouteRoute
    }
    '/$citySlug/community/learn/$slug/': {
      id: '/$citySlug/community/learn/$slug/'
      path: '/learn/$slug'
      fullPath: '/$citySlug/community/learn/$slug/'
      preLoaderRoute: typeof CitySlugCommunityLearnSlugIndexRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
    '/$citySlug/community/learn/$slug/$lesson': {
      id: '/$citySlug/community/learn/$slug/$lesson'
      path: '/learn/$slug/$lesson'
      fullPath: '/$citySlug/community/learn/$slug/$lesson'
      preLoaderRoute: typeof CitySlugCommunityLearnSlugLessonRouteImport
      parentRoute: typeof CitySlugCommunityRouteRoute
    }
  }
}

interface CitySlugAdminRouteRouteChildren {
  CitySlugAdminAnalyticsRoute: typeof CitySlugAdminAnalyticsRoute
  CitySlugAdminBadgesRoute: typeof CitySlugAdminBadgesRoute
  CitySlugAdminCitiesRoute: typeof CitySlugAdminCitiesRoute
  CitySlugAdminImportRoute: typeof CitySlugAdminImportRoute
  CitySlugAdminInviteRoute: typeof CitySlugAdminInviteRoute
  CitySlugAdminPostsRoute: typeof CitySlugAdminPostsRoute
  CitySlugAdminRolesRoute: typeof CitySlugAdminRolesRoute
  CitySlugAdminSettingsRoute: typeof CitySlugAdminSettingsRoute
  CitySlugAdminSpeakersRoute: typeof CitySlugAdminSpeakersRoute
  CitySlugAdminTiersRoute: typeof CitySlugAdminTiersRoute
  CitySlugAdminUsersRoute: typeof CitySlugAdminUsersRoute
  CitySlugAdminIndexRoute: typeof CitySlugAdminIndexRoute
  CitySlugAdminCoursesNewRoute: typeof CitySlugAdminCoursesNewRoute
  CitySlugAdminEmailIdRoute: typeof CitySlugAdminEmailIdRoute
  CitySlugAdminEmailAnalyticsRoute: typeof CitySlugAdminEmailAnalyticsRoute
  CitySlugAdminEmailAutomationsRoute: typeof CitySlugAdminEmailAutomationsRoute
  CitySlugAdminEmailContactsRoute: typeof CitySlugAdminEmailContactsRoute
  CitySlugAdminEmailNewRoute: typeof CitySlugAdminEmailNewRoute
  CitySlugAdminEmailSettingsRoute: typeof CitySlugAdminEmailSettingsRoute
  CitySlugAdminEmailTemplatesRoute: typeof CitySlugAdminEmailTemplatesRoute
  CitySlugAdminEventsNewRoute: typeof CitySlugAdminEventsNewRoute
  CitySlugAdminIndustriesSlugRoute: typeof CitySlugAdminIndustriesSlugRoute
  CitySlugAdminIndustriesNewRoute: typeof CitySlugAdminIndustriesNewRoute
  CitySlugAdminPagesIdRoute: typeof CitySlugAdminPagesIdRoute
  CitySlugAdminPagesHomeRoute: typeof CitySlugAdminPagesHomeRoute
  CitySlugAdminPagesNewRoute: typeof CitySlugAdminPagesNewRoute
  CitySlugAdminSocialSettingsRoute: typeof CitySlugAdminSocialSettingsRoute
  CitySlugAdminToolsAttendancePlannerRoute: typeof CitySlugAdminToolsAttendancePlannerRoute
  CitySlugAdminToolsAttendeeAnalyticsRoute: typeof CitySlugAdminToolsAttendeeAnalyticsRoute
  CitySlugAdminToolsQrGeneratorRoute: typeof CitySlugAdminToolsQrGeneratorRoute
  CitySlugAdminToolsSlideGeneratorRoute: typeof CitySlugAdminToolsSlideGeneratorRoute
  CitySlugAdminCoursesIndexRoute: typeof CitySlugAdminCoursesIndexRoute
  CitySlugAdminEmailIndexRoute: typeof CitySlugAdminEmailIndexRoute
  CitySlugAdminEventsIndexRoute: typeof CitySlugAdminEventsIndexRoute
  CitySlugAdminIndustriesIndexRoute: typeof CitySlugAdminIndustriesIndexRoute
  CitySlugAdminPagesIndexRoute: typeof CitySlugAdminPagesIndexRoute
  CitySlugAdminSocialIndexRoute: typeof CitySlugAdminSocialIndexRoute
  CitySlugAdminToolsIndexRoute: typeof CitySlugAdminToolsIndexRoute
  CitySlugAdminCoursesIdEditRoute: typeof CitySlugAdminCoursesIdEditRoute
}

const CitySlugAdminRouteRouteChildren: CitySlugAdminRouteRouteChildren = {
  CitySlugAdminAnalyticsRoute: CitySlugAdminAnalyticsRoute,
  CitySlugAdminBadgesRoute: CitySlugAdminBadgesRoute,
  CitySlugAdminCitiesRoute: CitySlugAdminCitiesRoute,
  CitySlugAdminImportRoute: CitySlugAdminImportRoute,
  CitySlugAdminInviteRoute: CitySlugAdminInviteRoute,
  CitySlugAdminPostsRoute: CitySlugAdminPostsRoute,
  CitySlugAdminRolesRoute: CitySlugAdminRolesRoute,
  CitySlugAdminSettingsRoute: CitySlugAdminSettingsRoute,
  CitySlugAdminSpeakersRoute: CitySlugAdminSpeakersRoute,
  CitySlugAdminTiersRoute: CitySlugAdminTiersRoute,
  CitySlugAdminUsersRoute: CitySlugAdminUsersRoute,
  CitySlugAdminIndexRoute: CitySlugAdminIndexRoute,
  CitySlugAdminCoursesNewRoute: CitySlugAdminCoursesNewRoute,
  CitySlugAdminEmailIdRoute: CitySlugAdminEmailIdRoute,
  CitySlugAdminEmailAnalyticsRoute: CitySlugAdminEmailAnalyticsRoute,
  CitySlugAdminEmailAutomationsRoute: CitySlugAdminEmailAutomationsRoute,
  CitySlugAdminEmailContactsRoute: CitySlugAdminEmailContactsRoute,
  CitySlugAdminEmailNewRoute: CitySlugAdminEmailNewRoute,
  CitySlugAdminEmailSettingsRoute: CitySlugAdminEmailSettingsRoute,
  CitySlugAdminEmailTemplatesRoute: CitySlugAdminEmailTemplatesRoute,
  CitySlugAdminEventsNewRoute: CitySlugAdminEventsNewRoute,
  CitySlugAdminIndustriesSlugRoute: CitySlugAdminIndustriesSlugRoute,
  CitySlugAdminIndustriesNewRoute: CitySlugAdminIndustriesNewRoute,
  CitySlugAdminPagesIdRoute: CitySlugAdminPagesIdRoute,
  CitySlugAdminPagesHomeRoute: CitySlugAdminPagesHomeRoute,
  CitySlugAdminPagesNewRoute: CitySlugAdminPagesNewRoute,
  CitySlugAdminSocialSettingsRoute: CitySlugAdminSocialSettingsRoute,
  CitySlugAdminToolsAttendancePlannerRoute:
    CitySlugAdminToolsAttendancePlannerRoute,
  CitySlugAdminToolsAttendeeAnalyticsRoute:
    CitySlugAdminToolsAttendeeAnalyticsRoute,
  CitySlugAdminToolsQrGeneratorRoute: CitySlugAdminToolsQrGeneratorRoute,
  CitySlugAdminToolsSlideGeneratorRoute: CitySlugAdminToolsSlideGeneratorRoute,
  CitySlugAdminCoursesIndexRoute: CitySlugAdminCoursesIndexRoute,
  CitySlugAdminEmailIndexRoute: CitySlugAdminEmailIndexRoute,
  CitySlugAdminEventsIndexRoute: CitySlugAdminEventsIndexRoute,
  CitySlugAdminIndustriesIndexRoute: CitySlugAdminIndustriesIndexRoute,
  CitySlugAdminPagesIndexRoute: CitySlugAdminPagesIndexRoute,
  CitySlugAdminSocialIndexRoute: CitySlugAdminSocialIndexRoute,
  CitySlugAdminToolsIndexRoute: CitySlugAdminToolsIndexRoute,
  CitySlugAdminCoursesIdEditRoute: CitySlugAdminCoursesIdEditRoute,
}

const CitySlugAdminRouteRouteWithChildren =
  CitySlugAdminRouteRoute._addFileChildren(CitySlugAdminRouteRouteChildren)

interface CitySlugCommunityRouteRouteChildren {
  CitySlugCommunityBookmarksRoute: typeof CitySlugCommunityBookmarksRoute
  CitySlugCommunityBugReportRoute: typeof CitySlugCommunityBugReportRoute
  CitySlugCommunityConnectionsRoute: typeof CitySlugCommunityConnectionsRoute
  CitySlugCommunityEventsRoute: typeof CitySlugCommunityEventsRoute
  CitySlugCommunityGuidelinesRoute: typeof CitySlugCommunityGuidelinesRoute
  CitySlugCommunityLeaderboardRoute: typeof CitySlugCommunityLeaderboardRoute
  CitySlugCommunityMembersRoute: typeof CitySlugCommunityMembersRoute
  CitySlugCommunityNotificationsRoute: typeof CitySlugCommunityNotificationsRoute
  CitySlugCommunitySearchRoute: typeof CitySlugCommunitySearchRoute
  CitySlugCommunityIndexRoute: typeof CitySlugCommunityIndexRoute
  CitySlugCommunityPostsIdRoute: typeof CitySlugCommunityPostsIdRoute
  CitySlugCommunityProfileIdRoute: typeof CitySlugCommunityProfileIdRoute
  CitySlugCommunitySettingsNotificationsRoute: typeof CitySlugCommunitySettingsNotificationsRoute
  CitySlugCommunitySettingsProfileRoute: typeof CitySlugCommunitySettingsProfileRoute
  CitySlugCommunityLearnIndexRoute: typeof CitySlugCommunityLearnIndexRoute
  CitySlugCommunityProfileIndexRoute: typeof CitySlugCommunityProfileIndexRoute
  CitySlugCommunityLearnSlugLessonRoute: typeof CitySlugCommunityLearnSlugLessonRoute
  CitySlugCommunityLearnSlugIndexRoute: typeof CitySlugCommunityLearnSlugIndexRoute
}

const CitySlugCommunityRouteRouteChildren: CitySlugCommunityRouteRouteChildren =
  {
    CitySlugCommunityBookmarksRoute: CitySlugCommunityBookmarksRoute,
    CitySlugCommunityBugReportRoute: CitySlugCommunityBugReportRoute,
    CitySlugCommunityConnectionsRoute: CitySlugCommunityConnectionsRoute,
    CitySlugCommunityEventsRoute: CitySlugCommunityEventsRoute,
    CitySlugCommunityGuidelinesRoute: CitySlugCommunityGuidelinesRoute,
    CitySlugCommunityLeaderboardRoute: CitySlugCommunityLeaderboardRoute,
    CitySlugCommunityMembersRoute: CitySlugCommunityMembersRoute,
    CitySlugCommunityNotificationsRoute: CitySlugCommunityNotificationsRoute,
    CitySlugCommunitySearchRoute: CitySlugCommunitySearchRoute,
    CitySlugCommunityIndexRoute: CitySlugCommunityIndexRoute,
    CitySlugCommunityPostsIdRoute: CitySlugCommunityPostsIdRoute,
    CitySlugCommunityProfileIdRoute: CitySlugCommunityProfileIdRoute,
    CitySlugCommunitySettingsNotificationsRoute:
      CitySlugCommunitySettingsNotificationsRoute,
    CitySlugCommunitySettingsProfileRoute:
      CitySlugCommunitySettingsProfileRoute,
    CitySlugCommunityLearnIndexRoute: CitySlugCommunityLearnIndexRoute,
    CitySlugCommunityProfileIndexRoute: CitySlugCommunityProfileIndexRoute,
    CitySlugCommunityLearnSlugLessonRoute:
      CitySlugCommunityLearnSlugLessonRoute,
    CitySlugCommunityLearnSlugIndexRoute: CitySlugCommunityLearnSlugIndexRoute,
  }

const CitySlugCommunityRouteRouteWithChildren =
  CitySlugCommunityRouteRoute._addFileChildren(
    CitySlugCommunityRouteRouteChildren,
  )

interface CitySlugRouteRouteChildren {
  CitySlugAdminRouteRoute: typeof CitySlugAdminRouteRouteWithChildren
  CitySlugCommunityRouteRoute: typeof CitySlugCommunityRouteRouteWithChildren
  CitySlugCoworkRoute: typeof CitySlugCoworkRoute
  CitySlugMembershipRoute: typeof CitySlugMembershipRoute
  CitySlugMerchRoute: typeof CitySlugMerchRoute
  CitySlugProfessionalsRoute: typeof CitySlugProfessionalsRoute
  CitySlugVibeCodersRoute: typeof CitySlugVibeCodersRoute
  CitySlugIndexRoute: typeof CitySlugIndexRoute
  CitySlugCitiesSlugRoute: typeof CitySlugCitiesSlugRoute
  CitySlugCoursesSlugRoute: typeof CitySlugCoursesSlugRoute
  CitySlugForSlugRoute: typeof CitySlugForSlugRoute
  CitySlugImpactLabAdminRoute: typeof CitySlugImpactLabAdminRoute
  CitySlugImpactLabPortalRoute: typeof CitySlugImpactLabPortalRoute
  CitySlugMyTalksIdRoute: typeof CitySlugMyTalksIdRoute
  CitySlugPSplatRoute: typeof CitySlugPSplatRoute
  CitySlugResourcesSlugRoute: typeof CitySlugResourcesSlugRoute
  CitySlugWebinarsClaudeCodeWebinarAustraliaRoute: typeof CitySlugWebinarsClaudeCodeWebinarAustraliaRoute
  CitySlugCoursesIndexRoute: typeof CitySlugCoursesIndexRoute
  CitySlugEventsIndexRoute: typeof CitySlugEventsIndexRoute
  CitySlugForIndexRoute: typeof CitySlugForIndexRoute
  CitySlugImpactLabIndexRoute: typeof CitySlugImpactLabIndexRoute
  CitySlugMyTalksIndexRoute: typeof CitySlugMyTalksIndexRoute
  CitySlugResourcesIndexRoute: typeof CitySlugResourcesIndexRoute
  CitySlugSpeakIndexRoute: typeof CitySlugSpeakIndexRoute
  CitySlugEventsSlugResourcesRoute: typeof CitySlugEventsSlugResourcesRoute
  CitySlugEventsClaudeImpactLabMelbourneSponsorRoute: typeof CitySlugEventsClaudeImpactLabMelbourneSponsorRoute
  CitySlugEventsSlugIndexRoute: typeof CitySlugEventsSlugIndexRoute
  CitySlugEventsClaudeImpactLabMelbourneIndexRoute: typeof CitySlugEventsClaudeImpactLabMelbourneIndexRoute
}

const CitySlugRouteRouteChildren: CitySlugRouteRouteChildren = {
  CitySlugAdminRouteRoute: CitySlugAdminRouteRouteWithChildren,
  CitySlugCommunityRouteRoute: CitySlugCommunityRouteRouteWithChildren,
  CitySlugCoworkRoute: CitySlugCoworkRoute,
  CitySlugMembershipRoute: CitySlugMembershipRoute,
  CitySlugMerchRoute: CitySlugMerchRoute,
  CitySlugProfessionalsRoute: CitySlugProfessionalsRoute,
  CitySlugVibeCodersRoute: CitySlugVibeCodersRoute,
  CitySlugIndexRoute: CitySlugIndexRoute,
  CitySlugCitiesSlugRoute: CitySlugCitiesSlugRoute,
  CitySlugCoursesSlugRoute: CitySlugCoursesSlugRoute,
  CitySlugForSlugRoute: CitySlugForSlugRoute,
  CitySlugImpactLabAdminRoute: CitySlugImpactLabAdminRoute,
  CitySlugImpactLabPortalRoute: CitySlugImpactLabPortalRoute,
  CitySlugMyTalksIdRoute: CitySlugMyTalksIdRoute,
  CitySlugPSplatRoute: CitySlugPSplatRoute,
  CitySlugResourcesSlugRoute: CitySlugResourcesSlugRoute,
  CitySlugWebinarsClaudeCodeWebinarAustraliaRoute:
    CitySlugWebinarsClaudeCodeWebinarAustraliaRoute,
  CitySlugCoursesIndexRoute: CitySlugCoursesIndexRoute,
  CitySlugEventsIndexRoute: CitySlugEventsIndexRoute,
  CitySlugForIndexRoute: CitySlugForIndexRoute,
  CitySlugImpactLabIndexRoute: CitySlugImpactLabIndexRoute,
  CitySlugMyTalksIndexRoute: CitySlugMyTalksIndexRoute,
  CitySlugResourcesIndexRoute: CitySlugResourcesIndexRoute,
  CitySlugSpeakIndexRoute: CitySlugSpeakIndexRoute,
  CitySlugEventsSlugResourcesRoute: CitySlugEventsSlugResourcesRoute,
  CitySlugEventsClaudeImpactLabMelbourneSponsorRoute:
    CitySlugEventsClaudeImpactLabMelbourneSponsorRoute,
  CitySlugEventsSlugIndexRoute: CitySlugEventsSlugIndexRoute,
  CitySlugEventsClaudeImpactLabMelbourneIndexRoute:
    CitySlugEventsClaudeImpactLabMelbourneIndexRoute,
}

const CitySlugRouteRouteWithChildren = CitySlugRouteRoute._addFileChildren(
  CitySlugRouteRouteChildren,
)

interface LoginRouteChildren {
  LoginSsoCallbackRoute: typeof LoginSsoCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSsoCallbackRoute: LoginSsoCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupSsoCallbackRoute: typeof SignupSsoCallbackRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSsoCallbackRoute: SignupSsoCallbackRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitySlugRouteRoute: CitySlugRouteRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  OfflineRoute: OfflineRoute,
  PricingRoute: PricingRoute,
  RemotionRoute: RemotionRoute,
  SignupRoute: SignupRouteWithChildren,
  SitemapRoute: SitemapRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiUploadRoute: ApiUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
