/**
 * One-off backfill for the per-tenant landing-content fields added alongside the
 * "tenantize landing content" work: `professionalStats`, `vibeCoderStats`,
 * `discordHeading` on `TenantSetting.config`.
 *
 * WHY: `scripts/seed-tenant.ts` seeds with `INSERT OR IGNORE`, so it never
 * updates an already-seeded tenant. A community seeded BEFORE these fields
 * existed (e.g. the live AU deploy) therefore resolves them from
 * `TENANT_CONFIG_DEFAULTS` — i.e. empty stats + the generic "…between meetups"
 * heading — silently dropping AU's stats and its "…between webinars" wording.
 * This backfill merges the region's values back in. New/unseeded communities get
 * the correct empty defaults automatically and need NOT run this.
 *
 * USAGE (run once per established deploy, against that account):
 *   bun scripts/backfill-landing-config.ts au > scripts/.landing-backfill.sql
 *   wrangler d1 execute DB --remote --file=scripts/.landing-backfill.sql
 *
 * Uses `json_set(…, json(…))` so it MERGES the three keys into the existing
 * config JSON without clobbering any admin edits.
 */
import { pathToFileURL } from "node:url";
import { type KnownRegion, REGION_CONFIGS } from "../src/lib/region";

/** Escape a JS string for a single-quoted SQLite literal. */
function sqlStr(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** SQL that merges a region's landing-content fields into its existing config. */
export function buildLandingBackfillSql(region: KnownRegion): string {
  const rc = REGION_CONFIGS[region];
  if (!rc) {
    throw new Error(
      `Unknown region "${region}" — expected one of: ${Object.keys(REGION_CONFIGS).join(", ")}`,
    );
  }
  return [
    `-- Landing-content backfill for "${region}" (generated by scripts/backfill-landing-config.ts).`,
    `-- Merges professionalStats / vibeCoderStats / discordHeading into the EXISTING`,
    `-- TenantSetting.config JSON (json_set never clobbers other admin-edited keys).`,
    `UPDATE "TenantSetting" SET "config" = json_set(`,
    `  "config",`,
    `  '$.professionalStats', json(${sqlStr(JSON.stringify(rc.professionalStats))}),`,
    `  '$.vibeCoderStats', json(${sqlStr(JSON.stringify(rc.vibeCoderStats))}),`,
    `  '$.discordHeading', ${sqlStr(rc.discordHeading)}`,
    `), "updatedAt" = CURRENT_TIMESTAMP WHERE "tenantId" = ${sqlStr(region)};`,
    ``,
  ].join("\n");
}

// CLI: `bun scripts/backfill-landing-config.ts [au|nz]` -> SQL on stdout.
// Portable entry guard (works on Windows too, unlike the older `file://${argv}`).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const region = (process.argv[2] ?? "au") as KnownRegion;
  process.stdout.write(buildLandingBackfillSql(region));
}
