#!/usr/bin/env node
/**
 * Build the mcp-ui Vite app and emit it as a TS module with the bundle
 * inlined as a string. The Next.js / Worker code then imports the
 * generated file as ordinary TypeScript.
 */
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const uiDir = resolve(repoRoot, "mcp-ui");
const distHtml = resolve(uiDir, "dist", "index.html");
const outDir = resolve(repoRoot, "src", "lib", "mcp");
const outFile = resolve(outDir, "ui-bundle.generated.ts");

if (!existsSync(resolve(uiDir, "node_modules"))) {
  console.log("[mcp-ui] Installing dependencies…");
  execSync("bun install", { cwd: uiDir, stdio: "inherit" });
}

console.log("[mcp-ui] Building Vite bundle…");
execSync("bun run build", { cwd: uiDir, stdio: "inherit" });

if (!existsSync(distHtml)) {
  console.error(`[mcp-ui] Expected output not found: ${distHtml}`);
  process.exit(1);
}

const html = readFileSync(distHtml, "utf8");

mkdirSync(outDir, { recursive: true });

const banner = "// AUTO-GENERATED by scripts/build-mcp-ui.mjs — DO NOT EDIT BY HAND.\n";
const body = `export const MCP_UI_HTML = ${JSON.stringify(html)};\n`;
writeFileSync(outFile, banner + body);

const kb = (html.length / 1024).toFixed(1);
console.log(`[mcp-ui] Wrote ${outFile} (${kb} KB)`);
