/**
 * Codegen: precompute the tenant-scope maps from the Prisma DMMF (in Node, where
 * `Prisma.dmmf` is available) and write them to a static TS file with no runtime
 * `Prisma.dmmf` access. This is what makes the tenant-isolation chokepoint
 * edge/workerd-safe: `Prisma.dmmf` THROWS in the Cloudflare edge runtime, so the
 * maps cannot be built at runtime there. The maps depend only on the static
 * Prisma SCHEMA (never on data), so generating them once at build time and
 * committing the result is correct.
 *
 * Wired into `scripts/prisma-generate.mjs` (run AFTER `prisma generate`, in a
 * fresh subprocess so the just-generated client is loaded). A drift-guard test
 * (`test/iso/tenant-scope-maps.test.ts`) recomputes from the live DMMF and fails
 * if the committed file is stale.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Prisma } from "@prisma/client";
import { deriveTenantScopeMaps } from "./lib/derive-tenant-scope-maps";

const models = Prisma.dmmf?.datamodel?.models;
if (!models) {
  throw new Error(
    "[gen-tenant-scope-maps] Prisma DMMF unavailable — run `prisma generate` first.",
  );
}

const { RELATIONS, SCALAR_FK_TO_REL } = deriveTenantScopeMaps(models);

const out = `// @generated by scripts/gen-tenant-scope-maps.ts — DO NOT EDIT BY HAND.
//
// Precomputed tenant-isolation maps for src/lib/tenant-scope.ts. Generated from
// the Prisma DMMF at build time (see scripts/prisma-generate.mjs) so the
// chokepoint NEVER touches \`Prisma.dmmf\` at runtime — that getter throws in the
// Cloudflare edge runtime. Plain object literals, no \`@prisma/client\` import:
// safe to load under workerd. Regenerate via \`prisma generate\` (the prebuild
// runs this). The drift guard test/iso/tenant-scope-maps.test.ts fails if stale.

/** model → (relationField → targetModel), from the generated DMMF. */
export const RELATIONS: Record<string, Record<string, string>> = ${JSON.stringify(
  RELATIONS,
  null,
  2,
)};

/** model → (scalarFKField → relationField) for FKs targeting a tenant-scoped model. */
export const SCALAR_FK_TO_REL: Record<string, Record<string, string>> = ${JSON.stringify(
  SCALAR_FK_TO_REL,
  null,
  2,
)};
`;

// Resolved from the repo root (the prebuild always runs from there).
const target = resolve(process.cwd(), "src/lib/tenant-scope-maps.generated.ts");
writeFileSync(target, out);
console.log(`[gen-tenant-scope-maps] wrote ${target}`);
