/**
 * Provision a NEW tenant into LOCAL D1 — the local-dev counterpart to the
 * `provisionTenant()` service (which runs inside the worker, where it has a
 * Prisma/D1 binding). A standalone tsx script has no such binding, so — exactly
 * like `scripts/seed-tenant.ts` — the pure `buildProvisionSql()` emits idempotent
 * SQL, and the CLI entry pipes it into `wrangler d1 execute --local`.
 *
 * Usage (wired as `npm run local:tenant:provision`):
 *   npm run local:tenant:provision -- <slug> <name> <ownerEmail> [customDomain]
 *   e.g. npm run local:tenant:provision -- acme "Acme Community" you@acme.test
 *
 * Then visit the tenant locally via subdomain tenancy — `acme.localhost:3000`
 * (browsers resolve `*.localhost` to loopback; no /etc/hosts needed).
 *
 * Creates: Tenant + TenantSetting (default `{}` config → getTenantConfig falls
 * back to TENANT_CONFIG_DEFAULTS) + the three system Roles + a placeholder owner
 * User (keyed by email, clerkId `provision_…`) + an owner UserTenant membership.
 *
 * The owner membership uses the seeded `super_admin` role (all permissions) —
 * NOT "owner", which is not in SYSTEM_ROLES/systemRoleSeeds and would resolve to
 * zero permissions (a latent bug in services/tenants.ts#provisionTenant, noted
 * separately). When the owner later signs up via Clerk with this email they hit
 * resolveSessionUser's existing-user LINK path (isNewSignup=false → no signup
 * auto-join collision) and inherit the membership.
 *
 * Idempotent: every statement is INSERT OR IGNORE, and the membership binds via
 * SELECT-by-email so it works whether the owner User was just created here or
 * already existed (e.g. from a prior signup).
 */
import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { ALL_PERMISSIONS, SYSTEM_ROLES } from "../src/lib/permissions";
import type { TenantConfig } from "../src/lib/tenant-config";
import { isValidTenantSlug } from "../src/lib/tenant-resolve";
import { buildReferenceSeedSql } from "./seed-reference";

/** Escape a JS string for a single-quoted SQLite literal. */
function sqlStr(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** Escape an optional string column (NULL when absent). */
function sqlNullable(value: string | null): string {
  return value === null ? "NULL" : sqlStr(value);
}

export interface ProvisionArgs {
  slug: string;
  name: string;
  ownerEmail: string;
  customDomain?: string | null;
  /**
   * Optional self-host branding written verbatim to `TenantSetting.config` as
   * JSON. A partial {@link TenantConfig}: `parseTenantConfig()` merges it over
   * `TENANT_CONFIG_DEFAULTS` when `getTenantConfig()` reads it, so only the
   * fields you override need be present. This is the additive, DB-backed branding
   * path — a self-host community brands itself WITHOUT editing `region.ts`.
   * Omitted → config stays `'{}'` (unchanged behaviour → getTenantConfig falls
   * back to TENANT_CONFIG_DEFAULTS, brandable later via the admin Tenant UI).
   */
  branding?: Partial<TenantConfig> | null;
  /** Injected for deterministic tests; the CLI generates random ids. */
  ids?: { user: string; membership: string; clerkSuffix: string };
}

/**
 * Build the idempotent provisioning SQL. Pure — the role-permission JSON is
 * derived from ALL_PERMISSIONS (never hand-typed), mirroring systemRoleSeeds.
 */
export function buildProvisionSql(args: ProvisionArgs): string {
  const slug = args.slug.toLowerCase();
  if (!isValidTenantSlug(slug)) {
    throw new Error(`Invalid tenant slug: "${slug}" (lowercase alphanumeric + internal hyphens, 2–39 chars, not reserved).`);
  }
  if (!args.ownerEmail.includes("@")) {
    throw new Error(`Invalid owner email: "${args.ownerEmail}".`);
  }
  const email = args.ownerEmail.toLowerCase().trim();
  const customDomain = args.customDomain?.trim() || null;
  const ids = args.ids ?? {
    user: `usr_${randomBytes(8).toString("hex")}`,
    membership: `ut_${randomBytes(8).toString("hex")}`,
    clerkSuffix: randomBytes(6).toString("hex"),
  };

  // Self-host branding → TenantSetting.config JSON. Default '{}' keeps the
  // existing behaviour byte-for-byte (getTenantConfig → TENANT_CONFIG_DEFAULTS).
  const configJson = args.branding ? JSON.stringify(args.branding) : "{}";

  const allPerms = JSON.stringify(ALL_PERMISSIONS);
  const roles = [
    { name: SYSTEM_ROLES.SUPER_ADMIN, permissions: allPerms },
    { name: SYSTEM_ROLES.ADMIN, permissions: allPerms },
    { name: SYSTEM_ROLES.MEMBER, permissions: "[]" },
  ];

  const lines: string[] = [
    `-- Provision tenant "${slug}" (generated by scripts/provision-tenant.ts). Idempotent: INSERT OR IGNORE throughout.`,
    `INSERT OR IGNORE INTO "Tenant" ("id","slug","customDomain","name","status","createdAt","updatedAt")`,
    `VALUES (${sqlStr(slug)}, ${sqlStr(slug)}, ${sqlNullable(customDomain)}, ${sqlStr(args.name)}, 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);`,
    ``,
    `INSERT OR IGNORE INTO "TenantSetting" ("id","tenantId","config","createdAt","updatedAt")`,
    `VALUES (${sqlStr(slug)}, ${sqlStr(slug)}, ${sqlStr(configJson)}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);`,
    ``,
  ];

  for (const r of roles) {
    lines.push(
      `INSERT OR IGNORE INTO "Role" ("tenantId","name","permissions","isSystem","createdAt","updatedAt")`,
      `VALUES (${sqlStr(slug)}, ${sqlStr(r.name)}, ${sqlStr(r.permissions)}, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);`,
      ``,
    );
  }

  lines.push(
    `-- Placeholder owner — claimed on Clerk signup with this email (resolveSessionUser link path).`,
    `INSERT OR IGNORE INTO "User" ("id","clerkId","email","name","role","importSource","isOnboarded","createdAt","updatedAt")`,
    `VALUES (${sqlStr(ids.user)}, ${sqlStr(`provision_${slug}_${ids.clerkSuffix}`)}, ${sqlStr(email)}, NULL, 'member', 'provision', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);`,
    ``,
    `-- Owner membership (super_admin = all permissions). SELECT-by-email binds whether the User was`,
    `-- just created above or already existed from a prior signup.`,
    `INSERT OR IGNORE INTO "UserTenant" ("id","tenantId","userId","role","createdAt","updatedAt")`,
    `SELECT ${sqlStr(ids.membership)}, ${sqlStr(slug)}, "id", ${sqlStr(SYSTEM_ROLES.SUPER_ADMIN)}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "User" WHERE "email" = ${sqlStr(email)};`,
    ``,
    // Default spaces + leaderboard levels so the tenant is usable immediately —
    // same content provisionTenant() seeds via Prisma (src/lib/tenant-defaults.ts).
    buildReferenceSeedSql(slug),
  );

  return lines.join("\n");
}

/**
 * Optional self-host branding for the CLI, from EITHER `TENANT_BRANDING_JSON`
 * (inline JSON) OR `TENANT_BRANDING_FILE` (path to a JSON file). Returns
 * `undefined` when neither is set → caller emits the default `'{}'` config.
 * Throws on malformed JSON so a typo fails loudly instead of silently seeding
 * placeholder branding (mirrors the seed-tenant "generated, not hand-typed"
 * rationale).
 */
function loadBrandingFromEnv(): Partial<TenantConfig> | undefined {
  const inline = process.env.TENANT_BRANDING_JSON;
  const file = process.env.TENANT_BRANDING_FILE;
  const raw = inline ?? (file ? readFileSync(file, "utf-8") : undefined);
  if (!raw) return undefined;
  const parsed = JSON.parse(raw);
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("TENANT_BRANDING_JSON/TENANT_BRANDING_FILE must be a JSON object of TenantConfig fields.");
  }
  return parsed as Partial<TenantConfig>;
}

// CLI: `tsx scripts/provision-tenant.ts <slug> <name> <ownerEmail> [customDomain]`
// → writes SQL to a temp file and applies it to LOCAL D1 via wrangler. Optional
// self-host branding via TENANT_BRANDING_JSON / TENANT_BRANDING_FILE (see above).
if (import.meta.url === `file://${process.argv[1]}`) {
  const [slug, name, ownerEmail, customDomain] = process.argv.slice(2);
  if (!slug || !name || !ownerEmail) {
    process.stderr.write(
      "Usage: npm run local:tenant:provision -- <slug> <name> <ownerEmail> [customDomain]\n" +
        "Optional branding: set TENANT_BRANDING_JSON='{...}' or TENANT_BRANDING_FILE=path/to/branding.json\n",
    );
    process.exit(1);
  }
  const sql = buildProvisionSql({ slug, name, ownerEmail, customDomain, branding: loadBrandingFromEnv() });
  const outFile = "scripts/.tenant-provision.sql";
  writeFileSync(outFile, sql);
  execFileSync("./node_modules/.bin/wrangler", ["d1", "execute", "DB", "--local", `--file=${outFile}`], {
    stdio: "inherit",
  });
  process.stderr.write(
    `\n✅ Provisioned tenant "${slug.toLowerCase()}". Visit it at ${slug.toLowerCase()}.localhost:3000 (subdomain tenancy).\n` +
      `   Sign up with ${ownerEmail} to claim the owner account.\n`,
  );
}
