/**
 * Default community reference data — Spaces + gamification LeaderboardLevels —
 * for ONE tenant. Both are tenant-scoped models (migration 0021 gave them a
 * `tenantId` and a composite `@@unique([tenantId, …])`), so they MUST be seeded
 * with an explicit tenantId or the chokepoint hides them from every tenant.
 *
 * This replaces the legacy `scripts/seed.sql` on multi-tenant deploys, which was
 * written pre-0021 and is now broken two ways: it seeds no tenantId (→ `''`,
 * invisible) and its `LeaderboardLevel ... ON CONFLICT (level)` upsert targets a
 * UNIQUE(level) that 0021 replaced with UNIQUE(tenantId, level) — hence
 * "ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint".
 *
 * Idempotent: every row is `INSERT OR IGNORE` keyed by the composite unique, so
 * re-running never clobbers a tenant's later edits to its own spaces/levels.
 *
 * The default content lives in `src/lib/tenant-defaults.ts` (shared with the
 * Prisma provisioning path); this module only renders it as tenant-scoped SQL.
 *
 * Usage (prints SQL to stdout; a caller pipes it into wrangler):
 *   tsx scripts/seed-reference.ts <tenantSlug>
 */
import { DEFAULT_LEADERBOARD_LEVELS as LEVELS, DEFAULT_SPACES as SPACES } from "../src/lib/tenant-defaults";

/** Escape a JS string for a single-quoted SQLite literal. */
function sqlStr(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** Tenant-scoped, idempotent SQL seeding default Spaces + LeaderboardLevels. */
export function buildReferenceSeedSql(tenantSlug: string): string {
  const t = sqlStr(tenantSlug.toLowerCase());
  const lines: string[] = [
    `-- Default reference data (Spaces + LeaderboardLevels) for tenant ${t}.`,
    `-- Generated by scripts/seed-reference.ts. Idempotent: INSERT OR IGNORE.`,
    `-- Spaces`,
  ];
  for (const s of SPACES) {
    lines.push(
      `INSERT OR IGNORE INTO "Space" ("id","tenantId","name","slug","icon","description","order","createdAt","updatedAt")`,
      `VALUES (lower(hex(randomblob(12))), ${t}, ${sqlStr(s.name)}, ${sqlStr(s.slug)}, ${sqlStr(s.icon)}, ${sqlStr(s.description)}, ${s.order}, datetime('now'), datetime('now'));`,
    );
  }
  lines.push(``, `-- Leaderboard levels`);
  for (const l of LEVELS) {
    lines.push(
      `INSERT OR IGNORE INTO "LeaderboardLevel" ("id","tenantId","level","name","icon","minPoints","color","createdAt")`,
      `VALUES (lower(hex(randomblob(12))), ${t}, ${l.level}, ${sqlStr(l.name)}, ${sqlStr(l.icon)}, ${l.minPoints}, ${sqlStr(l.color)}, datetime('now'));`,
    );
  }
  lines.push(``);
  return lines.join("\n");
}

// CLI: `tsx scripts/seed-reference.ts <tenantSlug>` -> SQL on stdout.
if (import.meta.url === `file://${process.argv[1]}`) {
  const slug = process.argv[2];
  if (!slug) {
    process.stderr.write("Usage: tsx scripts/seed-reference.ts <tenantSlug>\n");
    process.exit(1);
  }
  process.stdout.write(buildReferenceSeedSql(slug));
}
